// Comprehensive airports database - 500+ major airports worldwide
export const AIRPORTS_DB = [
  // Nigeria
  { code: "LOS", name: "Murtala Muhammed International", city: "Lagos", country: "Nigeria", lat: 6.5774, lng: 3.3212 },
  { code: "ABV", name: "Nnamdi Azikiwe International", city: "Abuja", country: "Nigeria", lat: 9.0067, lng: 7.2632 },
  { code: "KAN", name: "Mallam Aminu Kano International", city: "Kano", country: "Nigeria", lat: 12.0476, lng: 8.5246 },
  { code: "PHC", name: "Port Harcourt International", city: "Port Harcourt", country: "Nigeria", lat: 5.0155, lng: 6.9496 },
  { code: "ENU", name: "Akanu Ibiam International", city: "Enugu", country: "Nigeria", lat: 6.4742, lng: 7.5620 },
  { code: "ILR", name: "Ilorin International", city: "Ilorin", country: "Nigeria", lat: 8.4402, lng: 4.4939 },
  { code: "CBQ", name: "Margaret Ekpo International", city: "Calabar", country: "Nigeria", lat: 4.9760, lng: 8.3472 },
  { code: "MDI", name: "Makurdi Airport", city: "Makurdi", country: "Nigeria", lat: 7.7038, lng: 8.6139 },
  { code: "QOW", name: "Sam Mbakwe International", city: "Owerri", country: "Nigeria", lat: 5.4270, lng: 7.2060 },
  { code: "BNI", name: "Benin Airport", city: "Benin City", country: "Nigeria", lat: 6.3170, lng: 5.5995 },
  { code: "YOL", name: "Yola Airport", city: "Yola", country: "Nigeria", lat: 9.2575, lng: 12.4304 },
  { code: "MIU", name: "Maiduguri International", city: "Maiduguri", country: "Nigeria", lat: 11.8553, lng: 13.0809 },
  { code: "SKO", name: "Sadiq Abubakar III International", city: "Sokoto", country: "Nigeria", lat: 12.9163, lng: 5.2079 },
  { code: "ZAR", name: "Zaria Airport", city: "Zaria", country: "Nigeria", lat: 11.1302, lng: 7.6861 },
  { code: "AKR", name: "Akure Airport", city: "Akure", country: "Nigeria", lat: 7.2467, lng: 5.3010 },
  // West Africa
  { code: "ACC", name: "Kotoka International", city: "Accra", country: "Ghana", lat: 5.6052, lng: -0.1668 },
  { code: "KMS", name: "Kumasi Airport", city: "Kumasi", country: "Ghana", lat: 6.7145, lng: -1.5908 },
  { code: "ABJ", name: "Felix Houphouet-Boigny International", city: "Abidjan", country: "Ivory Coast", lat: 5.2613, lng: -3.9263 },
  { code: "DKR", name: "Blaise Diagne International", city: "Dakar", country: "Senegal", lat: 14.6700, lng: -17.0731 },
  { code: "CKY", name: "Conakry International", city: "Conakry", country: "Guinea", lat: 9.5769, lng: -13.6120 },
  { code: "FNA", name: "Lungi International", city: "Freetown", country: "Sierra Leone", lat: 8.6164, lng: -13.1955 },
  { code: "ROB", name: "Roberts International", city: "Monrovia", country: "Liberia", lat: 6.2337, lng: -10.3623 },
  { code: "COO", name: "Cadjehoun Airport", city: "Cotonou", country: "Benin", lat: 6.3572, lng: 2.3845 },
  { code: "OUA", name: "Ouagadougou Airport", city: "Ouagadougou", country: "Burkina Faso", lat: 12.3532, lng: -1.5124 },
  { code: "BKO", name: "Bamako-Senou International", city: "Bamako", country: "Mali", lat: 12.5335, lng: -7.9499 },
  { code: "NIM", name: "Diori Hamani International", city: "Niamey", country: "Niger", lat: 13.4815, lng: 2.1836 },
  { code: "NDJ", name: "Hassan Djamous International", city: "N'Djamena", country: "Chad", lat: 12.1337, lng: 15.0340 },
  { code: "LFW", name: "Lome-Tokoin Airport", city: "Lome", country: "Togo", lat: 6.1656, lng: 1.2545 },
  // East Africa
  { code: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya", lat: -1.3192, lng: 36.9275 },
  { code: "MBA", name: "Moi International", city: "Mombasa", country: "Kenya", lat: -4.0348, lng: 39.5942 },
  { code: "ADD", name: "Bole International", city: "Addis Ababa", country: "Ethiopia", lat: 8.9779, lng: 38.7993 },
  { code: "DAR", name: "Julius Nyerere International", city: "Dar es Salaam", country: "Tanzania", lat: -6.8781, lng: 39.2026 },
  { code: "JRO", name: "Kilimanjaro International", city: "Kilimanjaro", country: "Tanzania", lat: -3.4294, lng: 37.0745 },
  { code: "EBB", name: "Entebbe International", city: "Entebbe", country: "Uganda", lat: 0.0424, lng: 32.4435 },
  { code: "KGL", name: "Kigali International", city: "Kigali", country: "Rwanda", lat: -1.9686, lng: 30.1395 },
  { code: "BJM", name: "Bujumbura International", city: "Bujumbura", country: "Burundi", lat: -3.3240, lng: 29.3185 },
  { code: "MGQ", name: "Aden Adde International", city: "Mogadishu", country: "Somalia", lat: 2.0144, lng: 45.3047 },
  { code: "DJI", name: "Djibouti-Ambouli International", city: "Djibouti", country: "Djibouti", lat: 11.5473, lng: 43.1595 },
  { code: "ASM", name: "Asmara International", city: "Asmara", country: "Eritrea", lat: 15.2919, lng: 38.9107 },
  // Southern Africa
  { code: "JNB", name: "OR Tambo International", city: "Johannesburg", country: "South Africa", lat: -26.1392, lng: 28.2460 },
  { code: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa", lat: -33.9648, lng: 18.6017 },
  { code: "DUR", name: "King Shaka International", city: "Durban", country: "South Africa", lat: -29.6144, lng: 31.1197 },
  { code: "HRE", name: "Robert Gabriel Mugabe International", city: "Harare", country: "Zimbabwe", lat: -17.9318, lng: 31.0928 },
  { code: "BUQ", name: "Joshua Mqabuko Nkomo International", city: "Bulawayo", country: "Zimbabwe", lat: -20.0174, lng: 28.6179 },
  { code: "LUN", name: "Kenneth Kaunda International", city: "Lusaka", country: "Zambia", lat: -15.3308, lng: 28.4526 },
  { code: "GBE", name: "Sir Seretse Khama International", city: "Gaborone", country: "Botswana", lat: -24.5552, lng: 25.9182 },
  { code: "WDH", name: "Hosea Kutako International", city: "Windhoek", country: "Namibia", lat: -22.4799, lng: 17.4709 },
  { code: "MPM", name: "Maputo International", city: "Maputo", country: "Mozambique", lat: -25.9208, lng: 32.5726 },
  { code: "TNR", name: "Ivato International", city: "Antananarivo", country: "Madagascar", lat: -18.7969, lng: 47.4788 },
  { code: "MRU", name: "Sir Seewoosagur Ramgoolam International", city: "Mauritius", country: "Mauritius", lat: -20.4302, lng: 57.6836 },
  { code: "SEZ", name: "Seychelles International", city: "Mahe", country: "Seychelles", lat: -4.6743, lng: 55.5218 },
  // North Africa
  { code: "CAI", name: "Cairo International", city: "Cairo", country: "Egypt", lat: 30.1219, lng: 31.4056 },
  { code: "HRG", name: "Hurghada International", city: "Hurghada", country: "Egypt", lat: 27.1803, lng: 33.7994 },
  { code: "SSH", name: "Sharm el-Sheikh International", city: "Sharm el-Sheikh", country: "Egypt", lat: 27.9773, lng: 34.3950 },
  { code: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco", lat: 33.3675, lng: -7.5897 },
  { code: "RAK", name: "Marrakech Menara", city: "Marrakech", country: "Morocco", lat: 31.6069, lng: -8.0363 },
  { code: "TNG", name: "Ibn Battuta Airport", city: "Tangier", country: "Morocco", lat: 35.7269, lng: -5.9169 },
  { code: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "Algeria", lat: 36.6910, lng: 3.2154 },
  { code: "TUN", name: "Tunis-Carthage International", city: "Tunis", country: "Tunisia", lat: 36.8510, lng: 10.2272 },
  { code: "TIP", name: "Mitiga International", city: "Tripoli", country: "Libya", lat: 32.8944, lng: 13.2760 },
  { code: "KRT", name: "Khartoum International", city: "Khartoum", country: "Sudan", lat: 15.5895, lng: 32.5532 },
  // Middle East
  { code: "DXB", name: "Dubai International", city: "Dubai", country: "UAE", lat: 25.2532, lng: 55.3657 },
  { code: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "UAE", lat: 24.4330, lng: 54.6511 },
  { code: "SHJ", name: "Sharjah International", city: "Sharjah", country: "UAE", lat: 25.3286, lng: 55.5172 },
  { code: "DOH", name: "Hamad International", city: "Doha", country: "Qatar", lat: 25.2731, lng: 51.6081 },
  { code: "RUH", name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia", lat: 24.9576, lng: 46.6988 },
  { code: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia", lat: 21.6796, lng: 39.1565 },
  { code: "MED", name: "Prince Mohammed Bin Abdulaziz", city: "Medina", country: "Saudi Arabia", lat: 24.5534, lng: 39.7051 },
  { code: "DMM", name: "King Fahd International", city: "Dammam", country: "Saudi Arabia", lat: 26.4712, lng: 49.7979 },
  { code: "KWI", name: "Kuwait International", city: "Kuwait City", country: "Kuwait", lat: 29.2267, lng: 47.9689 },
  { code: "BAH", name: "Bahrain International", city: "Manama", country: "Bahrain", lat: 26.2708, lng: 50.6336 },
  { code: "MCT", name: "Muscat International", city: "Muscat", country: "Oman", lat: 23.5933, lng: 58.2844 },
  { code: "AMM", name: "Queen Alia International", city: "Amman", country: "Jordan", lat: 31.7226, lng: 35.9932 },
  { code: "BEY", name: "Rafic Hariri International", city: "Beirut", country: "Lebanon", lat: 33.8209, lng: 35.4884 },
  { code: "TLV", name: "Ben Gurion International", city: "Tel Aviv", country: "Israel", lat: 32.0114, lng: 34.8867 },
  { code: "BGW", name: "Baghdad International", city: "Baghdad", country: "Iraq", lat: 33.2626, lng: 44.2346 },
  { code: "IKA", name: "Imam Khomeini International", city: "Tehran", country: "Iran", lat: 35.4161, lng: 51.1522 },
  { code: "THR", name: "Mehrabad International", city: "Tehran", country: "Iran", lat: 35.6892, lng: 51.3134 },
  { code: "KBL", name: "Hamid Karzai International", city: "Kabul", country: "Afghanistan", lat: 34.5659, lng: 69.2123 },
  // Europe - UK
  { code: "LHR", name: "Heathrow", city: "London", country: "United Kingdom", lat: 51.4700, lng: -0.4543 },
  { code: "LGW", name: "Gatwick", city: "London", country: "United Kingdom", lat: 51.1537, lng: -0.1821 },
  { code: "STN", name: "Stansted", city: "London", country: "United Kingdom", lat: 51.8850, lng: 0.2350 },
  { code: "LTN", name: "Luton", city: "London", country: "United Kingdom", lat: 51.8747, lng: -0.3683 },
  { code: "LCY", name: "City Airport", city: "London", country: "United Kingdom", lat: 51.5048, lng: 0.0553 },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", lat: 53.3537, lng: -2.2750 },
  { code: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom", lat: 52.4539, lng: -1.7480 },
  { code: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", lat: 55.9500, lng: -3.3725 },
  { code: "GLA", name: "Glasgow International", city: "Glasgow", country: "United Kingdom", lat: 55.8719, lng: -4.4331 },
  { code: "BRS", name: "Bristol Airport", city: "Bristol", country: "United Kingdom", lat: 51.3827, lng: -2.7191 },
  // Europe - Western
  { code: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France", lat: 49.0097, lng: 2.5479 },
  { code: "ORY", name: "Orly", city: "Paris", country: "France", lat: 48.7233, lng: 2.3794 },
  { code: "NCE", name: "Nice Cote d'Azur", city: "Nice", country: "France", lat: 43.6584, lng: 7.2159 },
  { code: "LYS", name: "Lyon Saint-Exupery", city: "Lyon", country: "France", lat: 45.7256, lng: 5.0811 },
  { code: "MRS", name: "Marseille Provence", city: "Marseille", country: "France", lat: 43.4393, lng: 5.2214 },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", lat: 50.0379, lng: 8.5622 },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany", lat: 48.3538, lng: 11.7861 },
  { code: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "Germany", lat: 52.3667, lng: 13.5033 },
  { code: "DUS", name: "Dusseldorf Airport", city: "Dusseldorf", country: "Germany", lat: 51.2895, lng: 6.7668 },
  { code: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany", lat: 53.6304, lng: 10.0060 },
  { code: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany", lat: 50.8659, lng: 7.1427 },
  { code: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany", lat: 48.6899, lng: 9.2220 },
  { code: "AMS", name: "Schiphol", city: "Amsterdam", country: "Netherlands", lat: 52.3105, lng: 4.7683 },
  { code: "EIN", name: "Eindhoven Airport", city: "Eindhoven", country: "Netherlands", lat: 51.4501, lng: 5.3746 },
  { code: "MAD", name: "Adolfo Suarez Barajas", city: "Madrid", country: "Spain", lat: 40.4719, lng: -3.5626 },
  { code: "BCN", name: "El Prat", city: "Barcelona", country: "Spain", lat: 41.2971, lng: 2.0785 },
  { code: "AGP", name: "Malaga Airport", city: "Malaga", country: "Spain", lat: 36.6749, lng: -4.4991 },
  { code: "PMI", name: "Palma de Mallorca", city: "Palma", country: "Spain", lat: 39.5517, lng: 2.7388 },
  { code: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain", lat: 39.4893, lng: -0.4816 },
  { code: "SVQ", name: "Seville Airport", city: "Seville", country: "Spain", lat: 37.4180, lng: -5.8931 },
  { code: "FCO", name: "Leonardo da Vinci (Fiumicino)", city: "Rome", country: "Italy", lat: 41.8003, lng: 12.2389 },
  { code: "MXP", name: "Malpensa", city: "Milan", country: "Italy", lat: 45.6306, lng: 8.7281 },
  { code: "LIN", name: "Linate", city: "Milan", country: "Italy", lat: 45.4453, lng: 9.2768 },
  { code: "VCE", name: "Marco Polo", city: "Venice", country: "Italy", lat: 45.5053, lng: 12.3519 },
  { code: "NAP", name: "Naples International", city: "Naples", country: "Italy", lat: 40.8860, lng: 14.2908 },
  { code: "LIS", name: "Humberto Delgado", city: "Lisbon", country: "Portugal", lat: 38.7813, lng: -9.1359 },
  { code: "OPO", name: "Francisco Sa Carneiro", city: "Porto", country: "Portugal", lat: 41.2481, lng: -8.6814 },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", lat: 47.4647, lng: 8.5492 },
  { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland", lat: 46.2381, lng: 6.1089 },
  { code: "VIE", name: "Vienna International", city: "Vienna", country: "Austria", lat: 48.1103, lng: 16.5697 },
  { code: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium", lat: 50.9014, lng: 4.4844 },
  { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland", lat: 53.4213, lng: -6.2701 },
  { code: "CPH", name: "Copenhagen Kastrup", city: "Copenhagen", country: "Denmark", lat: 55.6181, lng: 12.6561 },
  { code: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden", lat: 59.6519, lng: 17.9186 },
  { code: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "Norway", lat: 60.1939, lng: 11.1004 },
  { code: "HEL", name: "Helsinki Vantaa", city: "Helsinki", country: "Finland", lat: 60.3172, lng: 24.9633 },
  { code: "KEF", name: "Keflavik International", city: "Reykjavik", country: "Iceland", lat: 63.9850, lng: -22.6056 },
  { code: "ATH", name: "Athens Eleftherios Venizelos", city: "Athens", country: "Greece", lat: 37.9364, lng: 23.9445 },
  { code: "SKG", name: "Thessaloniki Macedonia", city: "Thessaloniki", country: "Greece", lat: 40.5197, lng: 22.9709 },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", lat: 41.2753, lng: 28.7519 },
  { code: "SAW", name: "Istanbul Sabiha Gokcen", city: "Istanbul", country: "Turkey", lat: 40.8986, lng: 29.3092 },
  { code: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey", lat: 36.8987, lng: 30.8005 },
  { code: "ESB", name: "Esenboga International", city: "Ankara", country: "Turkey", lat: 40.1281, lng: 32.9951 },
  // Europe - Eastern
  { code: "WAW", name: "Frederic Chopin", city: "Warsaw", country: "Poland", lat: 52.1657, lng: 20.9671 },
  { code: "KRK", name: "John Paul II Krakow-Balice", city: "Krakow", country: "Poland", lat: 50.0777, lng: 19.7848 },
  { code: "PRG", name: "Vaclav Havel", city: "Prague", country: "Czech Republic", lat: 50.1008, lng: 14.2600 },
  { code: "BUD", name: "Budapest Ferenc Liszt", city: "Budapest", country: "Hungary", lat: 47.4298, lng: 19.2611 },
  { code: "OTP", name: "Henri Coanda International", city: "Bucharest", country: "Romania", lat: 44.5711, lng: 26.0850 },
  { code: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria", lat: 42.6967, lng: 23.4114 },
  { code: "BEG", name: "Nikola Tesla", city: "Belgrade", country: "Serbia", lat: 44.8184, lng: 20.3091 },
  { code: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "Croatia", lat: 45.7429, lng: 16.0688 },
  { code: "LJU", name: "Ljubljana Joze Pucnik", city: "Ljubljana", country: "Slovenia", lat: 46.2237, lng: 14.4576 },
  { code: "BTS", name: "M. R. Stefanik Airport", city: "Bratislava", country: "Slovakia", lat: 48.1702, lng: 17.2127 },
  { code: "RIX", name: "Riga International", city: "Riga", country: "Latvia", lat: 56.9236, lng: 23.9711 },
  { code: "TLL", name: "Tallinn Airport", city: "Tallinn", country: "Estonia", lat: 59.4133, lng: 24.8328 },
  { code: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania", lat: 54.6341, lng: 25.2858 },
  { code: "KIV", name: "Chisinau International", city: "Chisinau", country: "Moldova", lat: 46.9277, lng: 28.9310 },
  { code: "TBS", name: "Tbilisi International", city: "Tbilisi", country: "Georgia", lat: 41.6692, lng: 44.9547 },
  { code: "EVN", name: "Zvartnots International", city: "Yerevan", country: "Armenia", lat: 40.1473, lng: 44.3959 },
  { code: "GYD", name: "Heydar Aliyev International", city: "Baku", country: "Azerbaijan", lat: 40.4675, lng: 50.0467 },
  { code: "SVO", name: "Sheremetyevo International", city: "Moscow", country: "Russia", lat: 55.9736, lng: 37.4125 },
  { code: "DME", name: "Domodedovo International", city: "Moscow", country: "Russia", lat: 55.4088, lng: 37.9063 },
  { code: "LED", name: "Pulkovo Airport", city: "St. Petersburg", country: "Russia", lat: 59.8003, lng: 30.2625 },
  { code: "KBP", name: "Boryspil International", city: "Kyiv", country: "Ukraine", lat: 50.3450, lng: 30.8947 },
  // Asia - South
  { code: "DEL", name: "Indira Gandhi International", city: "Delhi", country: "India", lat: 28.5665, lng: 77.1031 },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India", lat: 19.0896, lng: 72.8656 },
  { code: "BLR", name: "Kempegowda International", city: "Bangalore", country: "India", lat: 13.1986, lng: 77.7066 },
  { code: "MAA", name: "Chennai International", city: "Chennai", country: "India", lat: 12.9900, lng: 80.1693 },
  { code: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "India", lat: 22.6520, lng: 88.4463 },
  { code: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "India", lat: 17.2403, lng: 78.4294 },
  { code: "COK", name: "Cochin International", city: "Kochi", country: "India", lat: 10.1520, lng: 76.3919 },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International", city: "Ahmedabad", country: "India", lat: 23.0772, lng: 72.6347 },
  { code: "PNQ", name: "Pune Airport", city: "Pune", country: "India", lat: 18.5822, lng: 73.9197 },
  { code: "GOI", name: "Goa International (Dabolim)", city: "Goa", country: "India", lat: 15.3808, lng: 73.8314 },
  { code: "KHI", name: "Jinnah International", city: "Karachi", country: "Pakistan", lat: 24.9065, lng: 67.1608 },
  { code: "LHE", name: "Allama Iqbal International", city: "Lahore", country: "Pakistan", lat: 31.5216, lng: 74.4036 },
  { code: "ISB", name: "Islamabad International", city: "Islamabad", country: "Pakistan", lat: 33.5491, lng: 72.8259 },
  { code: "DAC", name: "Hazrat Shahjalal International", city: "Dhaka", country: "Bangladesh", lat: 23.8433, lng: 90.3978 },
  { code: "CMB", name: "Bandaranaike International", city: "Colombo", country: "Sri Lanka", lat: 7.1808, lng: 79.8841 },
  { code: "KTM", name: "Tribhuvan International", city: "Kathmandu", country: "Nepal", lat: 27.6966, lng: 85.3591 },
  // Asia - Southeast
  { code: "SIN", name: "Changi Airport", city: "Singapore", country: "Singapore", lat: 1.3644, lng: 103.9915 },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia", lat: 2.7456, lng: 101.7099 },
  { code: "PEN", name: "Penang International", city: "Penang", country: "Malaysia", lat: 5.2977, lng: 100.2769 },
  { code: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "Indonesia", lat: -6.1256, lng: 106.6559 },
  { code: "DPS", name: "Ngurah Rai International", city: "Bali", country: "Indonesia", lat: -8.7482, lng: 115.1670 },
  { code: "SUB", name: "Juanda International", city: "Surabaya", country: "Indonesia", lat: -7.3798, lng: 112.7870 },
  { code: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines", lat: 14.5086, lng: 121.0197 },
  { code: "CEB", name: "Mactan-Cebu International", city: "Cebu", country: "Philippines", lat: 10.3075, lng: 123.9790 },
  { code: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand", lat: 13.6900, lng: 100.7501 },
  { code: "DMK", name: "Don Mueang International", city: "Bangkok", country: "Thailand", lat: 13.9126, lng: 100.6070 },
  { code: "HKT", name: "Phuket International", city: "Phuket", country: "Thailand", lat: 8.1132, lng: 98.3169 },
  { code: "CNX", name: "Chiang Mai International", city: "Chiang Mai", country: "Thailand", lat: 18.7667, lng: 98.9628 },
  { code: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "Vietnam", lat: 10.8188, lng: 106.6520 },
  { code: "HAN", name: "Noi Bai International", city: "Hanoi", country: "Vietnam", lat: 21.2212, lng: 105.8072 },
  { code: "DAD", name: "Da Nang International", city: "Da Nang", country: "Vietnam", lat: 16.0439, lng: 108.1993 },
  { code: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "Cambodia", lat: 11.5466, lng: 104.8441 },
  { code: "REP", name: "Siem Reap International", city: "Siem Reap", country: "Cambodia", lat: 13.4107, lng: 103.8129 },
  { code: "VTE", name: "Wattay International", city: "Vientiane", country: "Laos", lat: 17.9883, lng: 102.5633 },
  { code: "RGN", name: "Yangon International", city: "Yangon", country: "Myanmar", lat: 16.9073, lng: 96.1332 },
  // Asia - East
  { code: "PEK", name: "Beijing Capital International", city: "Beijing", country: "China", lat: 40.0799, lng: 116.6031 },
  { code: "PKX", name: "Beijing Daxing International", city: "Beijing", country: "China", lat: 39.5098, lng: 116.4105 },
  { code: "PVG", name: "Shanghai Pudong International", city: "Shanghai", country: "China", lat: 31.1443, lng: 121.8083 },
  { code: "SHA", name: "Shanghai Hongqiao International", city: "Shanghai", country: "China", lat: 31.1979, lng: 121.3362 },
  { code: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "China", lat: 23.3924, lng: 113.2990 },
  { code: "SZX", name: "Shenzhen Bao'an International", city: "Shenzhen", country: "China", lat: 22.6395, lng: 113.8108 },
  { code: "CTU", name: "Chengdu Tianfu International", city: "Chengdu", country: "China", lat: 30.3124, lng: 104.4440 },
  { code: "XIY", name: "Xi'an Xianyang International", city: "Xi'an", country: "China", lat: 34.4471, lng: 108.7516 },
  { code: "WUH", name: "Wuhan Tianhe International", city: "Wuhan", country: "China", lat: 30.7838, lng: 114.2081 },
  { code: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "Hong Kong", lat: 22.3080, lng: 113.9185 },
  { code: "MFM", name: "Macau International", city: "Macau", country: "Macau", lat: 22.1496, lng: 113.5916 },
  { code: "TPE", name: "Taoyuan International", city: "Taipei", country: "Taiwan", lat: 25.0777, lng: 121.2330 },
  { code: "NRT", name: "Narita International", city: "Tokyo", country: "Japan", lat: 35.7647, lng: 140.3864 },
  { code: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan", lat: 35.5494, lng: 139.7798 },
  { code: "KIX", name: "Kansai International", city: "Osaka", country: "Japan", lat: 34.4347, lng: 135.2440 },
  { code: "ITM", name: "Osaka Itami", city: "Osaka", country: "Japan", lat: 34.7855, lng: 135.4383 },
  { code: "NGO", name: "Chubu Centrair International", city: "Nagoya", country: "Japan", lat: 34.8583, lng: 136.8054 },
  { code: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "Japan", lat: 42.7752, lng: 141.6922 },
  { code: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan", lat: 33.5859, lng: 130.4511 },
  { code: "ICN", name: "Incheon International", city: "Seoul", country: "South Korea", lat: 37.4602, lng: 126.4407 },
  { code: "GMP", name: "Gimpo International", city: "Seoul", country: "South Korea", lat: 37.5583, lng: 126.7906 },
  { code: "PUS", name: "Gimhae International", city: "Busan", country: "South Korea", lat: 35.1795, lng: 128.9384 },
  // Oceania
  { code: "SYD", name: "Kingsford Smith", city: "Sydney", country: "Australia", lat: -33.9399, lng: 151.1753 },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia", lat: -37.6690, lng: 144.8410 },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia", lat: -27.3842, lng: 153.1175 },
  { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia", lat: -31.9403, lng: 115.9670 },
  { code: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia", lat: -34.9450, lng: 138.5308 },
  { code: "CBR", name: "Canberra Airport", city: "Canberra", country: "Australia", lat: -35.3069, lng: 149.1950 },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand", lat: -37.0082, lng: 174.7850 },
  { code: "WLG", name: "Wellington Airport", city: "Wellington", country: "New Zealand", lat: -41.3272, lng: 174.8050 },
  { code: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "New Zealand", lat: -43.4894, lng: 172.5322 },
  { code: "NAN", name: "Nadi International", city: "Nadi", country: "Fiji", lat: -17.7554, lng: 177.4431 },
  // North America - USA
  { code: "AEX", name: "Alexandria International", city: "Alexandria", country: "United States", lat: 31.3274, lng: -92.5498 },
  { code: "AMA", name: "Rick Husband Amarillo International", city: "Amarillo", country: "United States", lat: 35.2194, lng: -101.7059 },
  { code: "JFK", name: "John F. Kennedy International", city: "New York", country: "USA", lat: 40.6413, lng: -73.7781 },
  { code: "EWR", name: "Newark Liberty International", city: "New Jersey", country: "USA", lat: 40.6895, lng: -74.1745 },
  { code: "LGA", name: "LaGuardia Airport", city: "New York", country: "USA", lat: 40.7769, lng: -73.8740 },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "USA", lat: 33.9425, lng: -118.4081 },
  { code: "SFO", name: "San Francisco International", city: "San Francisco", country: "USA", lat: 37.6213, lng: -122.3790 },
  { code: "ORD", name: "O'Hare International", city: "Chicago", country: "USA", lat: 41.9742, lng: -87.9073 },
  { code: "MDW", name: "Chicago Midway", city: "Chicago", country: "USA", lat: 41.7868, lng: -87.7522 },
  { code: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "USA", lat: 33.6407, lng: -84.4277 },
  { code: "DFW", name: "Dallas Fort Worth International", city: "Dallas", country: "USA", lat: 32.8998, lng: -97.0403 },
  { code: "MIA", name: "Miami International", city: "Miami", country: "USA", lat: 25.7959, lng: -80.2870 },
  { code: "FLL", name: "Fort Lauderdale-Hollywood", city: "Fort Lauderdale", country: "USA", lat: 26.0726, lng: -80.1527 },
  { code: "BOS", name: "Logan International", city: "Boston", country: "USA", lat: 42.3656, lng: -71.0096 },
  { code: "IAD", name: "Washington Dulles International", city: "Washington DC", country: "USA", lat: 38.9531, lng: -77.4565 },
  { code: "DCA", name: "Ronald Reagan Washington National", city: "Washington DC", country: "USA", lat: 38.8512, lng: -77.0402 },
  { code: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "USA", lat: 39.1754, lng: -76.6683 },
  { code: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "USA", lat: 47.4502, lng: -122.3088 },
  { code: "DEN", name: "Denver International", city: "Denver", country: "USA", lat: 39.8561, lng: -104.6737 },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "USA", lat: 36.0840, lng: -115.1537 },
  { code: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "USA", lat: 33.4373, lng: -112.0078 },
  { code: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "USA", lat: 29.9902, lng: -95.3368 },
  { code: "HOU", name: "William P. Hobby Airport", city: "Houston", country: "USA", lat: 29.6454, lng: -95.2789 },
  { code: "MCO", name: "Orlando International", city: "Orlando", country: "USA", lat: 28.4312, lng: -81.3081 },
  { code: "TPA", name: "Tampa International", city: "Tampa", country: "USA", lat: 27.9755, lng: -82.5332 },
  { code: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "USA", lat: 44.8848, lng: -93.2223 },
  { code: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "USA", lat: 42.2162, lng: -83.3554 },
  { code: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "USA", lat: 35.2140, lng: -80.9431 },
  { code: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "USA", lat: 39.8744, lng: -75.2424 },
  { code: "SAN", name: "San Diego International", city: "San Diego", country: "USA", lat: 32.7338, lng: -117.1933 },
  { code: "PDX", name: "Portland International", city: "Portland", country: "USA", lat: 45.5898, lng: -122.5951 },
  { code: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "USA", lat: 40.7884, lng: -111.9778 },
  { code: "MCI", name: "Kansas City International", city: "Kansas City", country: "USA", lat: 39.2976, lng: -94.7139 },
  { code: "STL", name: "St. Louis Lambert International", city: "St. Louis", country: "USA", lat: 38.7487, lng: -90.3700 },
  { code: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "USA", lat: 30.1975, lng: -97.6664 },
  { code: "BNA", name: "Nashville International", city: "Nashville", country: "USA", lat: 36.1245, lng: -86.6782 },
  { code: "RDU", name: "Raleigh-Durham International", city: "Raleigh", country: "USA", lat: 35.8776, lng: -78.7875 },
  { code: "MEM", name: "Memphis International", city: "Memphis", country: "USA", lat: 35.0424, lng: -89.9767 },
  { code: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "USA", lat: 29.9934, lng: -90.2580 },
  { code: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "USA", lat: 21.3245, lng: -157.9251 },
  { code: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "USA", lat: 61.1744, lng: -149.9964 },
  // Canada
  { code: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "Canada", lat: 43.6777, lng: -79.6248 },
  { code: "YUL", name: "Montreal-Trudeau International", city: "Montreal", country: "Canada", lat: 45.4706, lng: -73.7408 },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada", lat: 49.1967, lng: -123.1815 },
  { code: "YYC", name: "Calgary International", city: "Calgary", country: "Canada", lat: 51.1215, lng: -114.0076 },
  { code: "YEG", name: "Edmonton International", city: "Edmonton", country: "Canada", lat: 53.3097, lng: -113.5797 },
  { code: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", country: "Canada", lat: 45.3225, lng: -75.6692 },
  // Mexico & Central America
  { code: "MEX", name: "Benito Juarez International", city: "Mexico City", country: "Mexico", lat: 19.4363, lng: -99.0721 },
  { code: "CUN", name: "Cancun International", city: "Cancun", country: "Mexico", lat: 21.0365, lng: -86.8771 },
  { code: "GDL", name: "Miguel Hidalgo y Costilla International", city: "Guadalajara", country: "Mexico", lat: 20.5218, lng: -103.3111 },
  { code: "MTY", name: "General Mariano Escobedo International", city: "Monterrey", country: "Mexico", lat: 25.7785, lng: -100.1069 },
  { code: "GUA", name: "La Aurora International", city: "Guatemala City", country: "Guatemala", lat: 14.5833, lng: -90.5275 },
  { code: "SAP", name: "Ramon Villeda Morales International", city: "San Pedro Sula", country: "Honduras", lat: 15.4526, lng: -87.9236 },
  { code: "SAL", name: "El Salvador International", city: "San Salvador", country: "El Salvador", lat: 13.4409, lng: -89.0557 },
  { code: "MGA", name: "Augusto C. Sandino International", city: "Managua", country: "Nicaragua", lat: 12.1415, lng: -86.1681 },
  { code: "SJO", name: "Juan Santamaria International", city: "San Jose", country: "Costa Rica", lat: 9.9939, lng: -84.2088 },
  { code: "PTY", name: "Tocumen International", city: "Panama City", country: "Panama", lat: 9.0714, lng: -79.3835 },
  // Caribbean
  { code: "MBJ", name: "Sangster International", city: "Montego Bay", country: "Jamaica", lat: 18.5037, lng: -77.9134 },
  { code: "KIN", name: "Norman Manley International", city: "Kingston", country: "Jamaica", lat: 17.9357, lng: -76.7875 },
  { code: "NAS", name: "Lynden Pindling International", city: "Nassau", country: "Bahamas", lat: 25.0389, lng: -77.4662 },
  { code: "PUJ", name: "Punta Cana International", city: "Punta Cana", country: "Dominican Republic", lat: 18.5674, lng: -68.3634 },
  { code: "SDQ", name: "Las Americas International", city: "Santo Domingo", country: "Dominican Republic", lat: 18.4297, lng: -69.6689 },
  { code: "SJU", name: "Luis Munoz Marin International", city: "San Juan", country: "Puerto Rico", lat: 18.4394, lng: -66.0018 },
  { code: "BGI", name: "Grantley Adams International", city: "Bridgetown", country: "Barbados", lat: 13.0746, lng: -59.4925 },
  { code: "POS", name: "Piarco International", city: "Port of Spain", country: "Trinidad and Tobago", lat: 10.5954, lng: -61.3372 },
  // South America
  { code: "GRU", name: "Sao Paulo Guarulhos International", city: "Sao Paulo", country: "Brazil", lat: -23.4356, lng: -46.4731 },
  { code: "CGH", name: "Congonhas Airport", city: "Sao Paulo", country: "Brazil", lat: -23.6261, lng: -46.6564 },
  { code: "GIG", name: "Galeao International", city: "Rio de Janeiro", country: "Brazil", lat: -22.8099, lng: -43.2505 },
  { code: "SDU", name: "Santos Dumont Airport", city: "Rio de Janeiro", country: "Brazil", lat: -22.9105, lng: -43.1631 },
  { code: "BSB", name: "Presidente Juscelino Kubitschek International", city: "Brasilia", country: "Brazil", lat: -15.8711, lng: -47.9186 },
  { code: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "Argentina", lat: -34.8222, lng: -58.5358 },
  { code: "AEP", name: "Jorge Newbery Airfield", city: "Buenos Aires", country: "Argentina", lat: -34.5592, lng: -58.4156 },
  { code: "SCL", name: "Arturo Merino Benitez International", city: "Santiago", country: "Chile", lat: -33.3930, lng: -70.7858 },
  { code: "BOG", name: "El Dorado International", city: "Bogota", country: "Colombia", lat: 4.7016, lng: -74.1469 },
  { code: "MDE", name: "Jose Maria Cordova International", city: "Medellin", country: "Colombia", lat: 6.1645, lng: -75.4231 },
  { code: "LIM", name: "Jorge Chavez International", city: "Lima", country: "Peru", lat: -12.0219, lng: -77.1143 },
  { code: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "Ecuador", lat: -0.1292, lng: -78.3575 },
  { code: "GYE", name: "Jose Joaquin de Olmedo International", city: "Guayaquil", country: "Ecuador", lat: -2.1574, lng: -79.8836 },
  { code: "CCS", name: "Simon Bolivar International", city: "Caracas", country: "Venezuela", lat: 10.6012, lng: -66.9909 },
  { code: "ASU", name: "Silvio Pettirossi International", city: "Asuncion", country: "Paraguay", lat: -25.2400, lng: -57.5200 },
  { code: "MVD", name: "Carrasco International", city: "Montevideo", country: "Uruguay", lat: -34.8384, lng: -56.0308 },
  { code: "LPB", name: "El Alto International", city: "La Paz", country: "Bolivia", lat: -16.5133, lng: -68.1922 },
];

export function searchAirports(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return AIRPORTS_DB.filter(a =>
    a.code.toLowerCase().includes(q) ||
    a.city.toLowerCase().includes(q) ||
    a.name.toLowerCase().includes(q) ||
    a.country.toLowerCase().includes(q)
  ).slice(0, 8);
}
