// Comprehensive airports database - 1000+ major airports worldwide
export const AIRPORTS_DB = [
  // Nigeria
  { code: "LOS", name: "Murtala Muhammed International", city: "Lagos", country: "Nigeria", lat: 6.5774, lng: 3.3212 },
  { code: "ABV", name: "Nnamdi Azikiwe International", city: "Abuja", country: "Nigeria", lat: 9.0067, lng: 7.2632 },
  { code: "KAN", name: "Mallam Aminu Kano International", city: "Kano", country: "Nigeria", lat: 12.0476, lng: 8.5246 },
  { code: "PHC", name: "Port Harcourt International", city: "Port Harcourt", country: "Nigeria", lat: 5.0155, lng: 6.9496 },
  { code: "ENU", name: "Akanu Ibiam International", city: "Enugu", country: "Nigeria", lat: 6.4742, lng: 7.5620 },
  { code: "ILR", name: "Ilorin International", city: "Ilorin", country: "Nigeria", lat: 8.4402, lng: 4.4939 },
  { code: "CBQ", name: "Margaret Ekpo International", city: "Calabar", country: "Nigeria", lat: 4.9760, lng: 8.3472 },
  { code: "MDI", name: "Makurdi Airport", city: "Makurdi", country: "Nigeria", lat: 7.7038, lng: 8.6139 },
  { code: "QOW", name: "Sam Mbakwe International", city: "Owerri", country: "Nigeria", lat: 5.4270, lng: 7.2060 },
  { code: "BNI", name: "Benin Airport", city: "Benin City", country: "Nigeria", lat: 6.3170, lng: 5.5995 },
  { code: "YOL", name: "Yola Airport", city: "Yola", country: "Nigeria", lat: 9.2575, lng: 12.4304 },
  { code: "MIU", name: "Maiduguri International", city: "Maiduguri", country: "Nigeria", lat: 11.8553, lng: 13.0809 },
  { code: "SKO", name: "Sadiq Abubakar III International", city: "Sokoto", country: "Nigeria", lat: 12.9163, lng: 5.2079 },
  { code: "ZAR", name: "Zaria Airport", city: "Zaria", country: "Nigeria", lat: 11.1302, lng: 7.6861 },
  { code: "AKR", name: "Akure Airport", city: "Akure", country: "Nigeria", lat: 7.2467, lng: 5.3010 },
  { code: "ABB", name: "Asaba International", city: "Asaba", country: "Nigeria", lat: 6.2042, lng: 6.6653 },
  { code: "GMO", name: "Gombe Lawanti International", city: "Gombe", country: "Nigeria", lat: 10.2983, lng: 10.8964 },
  { code: "JOS", name: "Yakubu Gowon Airport", city: "Jos", country: "Nigeria", lat: 9.6398, lng: 8.8696 },
  { code: "KAD", name: "Kaduna Airport", city: "Kaduna", country: "Nigeria", lat: 10.6960, lng: 7.3201 },
  { code: "BCU", name: "Bauchi State Airport", city: "Bauchi", country: "Nigeria", lat: 10.4828, lng: 9.7440 },
  { code: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", country: "USA", lat: 33.5629, lng: -86.7535 },
{ code: "HSV", name: "Huntsville International", city: "Huntsville", country: "USA", lat: 34.6372, lng: -86.7751 },
{ code: "MGM", name: "Montgomery Regional", city: "Montgomery", country: "USA", lat: 32.3006, lng: -86.3939 },
{ code: "MOB", name: "Mobile Regional", city: "Mobile", country: "USA", lat: 30.6912, lng: -88.2428 },
{ code: "TUS", name: "Tucson International", city: "Tucson", country: "USA", lat: 32.1161, lng: -110.9410 },

  // West Africa
  { code: "ACC", name: "Kotoka International", city: "Accra", country: "Ghana", lat: 5.6052, lng: -0.1668 },
  { code: "KMS", name: "Kumasi Airport", city: "Kumasi", country: "Ghana", lat: 6.7145, lng: -1.5908 },
  { code: "TML", name: "Tamale Airport", city: "Tamale", country: "Ghana", lat: 9.5572, lng: -0.8632 },
  { code: "ABJ", name: "Felix Houphouet-Boigny International", city: "Abidjan", country: "Ivory Coast", lat: 5.2613, lng: -3.9263 },
  { code: "DKR", name: "Blaise Diagne International", city: "Dakar", country: "Senegal", lat: 14.6700, lng: -17.0731 },
  { code: "ZIG", name: "Ziguinchor Airport", city: "Ziguinchor", country: "Senegal", lat: 12.5556, lng: -16.2818 },
  { code: "CKY", name: "Conakry International", city: "Conakry", country: "Guinea", lat: 9.5769, lng: -13.6120 },
  { code: "FNA", name: "Lungi International", city: "Freetown", country: "Sierra Leone", lat: 8.6164, lng: -13.1955 },
  { code: "ROB", name: "Roberts International", city: "Monrovia", country: "Liberia", lat: 6.2337, lng: -10.3623 },
  { code: "COO", name: "Cadjehoun Airport", city: "Cotonou", country: "Benin", lat: 6.3572, lng: 2.3845 },
  { code: "OUA", name: "Ouagadougou Airport", city: "Ouagadougou", country: "Burkina Faso", lat: 12.3532, lng: -1.5124 },
  { code: "BKO", name: "Bamako-Senou International", city: "Bamako", country: "Mali", lat: 12.5335, lng: -7.9499 },
  { code: "NIM", name: "Diori Hamani International", city: "Niamey", country: "Niger", lat: 13.4815, lng: 2.1836 },
  { code: "NDJ", name: "Hassan Djamous International", city: "N'Djamena", country: "Chad", lat: 12.1337, lng: 15.0340 },
  { code: "LFW", name: "Lome-Tokoin Airport", city: "Lome", country: "Togo", lat: 6.1656, lng: 1.2545 },
  { code: "BJL", name: "Banjul International", city: "Banjul", country: "Gambia", lat: 13.3380, lng: -16.6522 },
  { code: "OXB", name: "Osvaldo Vieira International", city: "Bissau", country: "Guinea-Bissau", lat: 11.8948, lng: -15.6537 },
  { code: "SSG", name: "Malabo International", city: "Malabo", country: "Equatorial Guinea", lat: 3.7553, lng: 8.7087 },
  { code: "LBV", name: "Leon M'ba International", city: "Libreville", country: "Gabon", lat: 0.4586, lng: 9.4123 },
  { code: "BZV", name: "Maya-Maya Airport", city: "Brazzaville", country: "Republic of Congo", lat: -4.2517, lng: 15.2531 },
  { code: "FIH", name: "N'djili International", city: "Kinshasa", country: "DR Congo", lat: -4.3857, lng: 15.4446 },
  { code: "FBM", name: "Lubumbashi International", city: "Lubumbashi", country: "DR Congo", lat: -11.5913, lng: 27.5309 },
  { code: "SXF", name: "Sao Tome International", city: "Sao Tome", country: "Sao Tome and Principe", lat: 0.3782, lng: 6.7122 },

  // East Africa
  { code: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya", lat: -1.3192, lng: 36.9275 },
  { code: "MBA", name: "Moi International", city: "Mombasa", country: "Kenya", lat: -4.0348, lng: 39.5942 },
  { code: "KIS", name: "Kisumu International", city: "Kisumu", country: "Kenya", lat: -0.0861, lng: 34.7290 },
  { code: "ADD", name: "Bole International", city: "Addis Ababa", country: "Ethiopia", lat: 8.9779, lng: 38.7993 },
  { code: "DIR", name: "Dire Dawa Airport", city: "Dire Dawa", country: "Ethiopia", lat: 9.6247, lng: 41.8542 },
  { code: "DAR", name: "Julius Nyerere International", city: "Dar es Salaam", country: "Tanzania", lat: -6.8781, lng: 39.2026 },
  { code: "JRO", name: "Kilimanjaro International", city: "Kilimanjaro", country: "Tanzania", lat: -3.4294, lng: 37.0745 },
  { code: "ZNZ", name: "Abeid Amani Karume International", city: "Zanzibar", country: "Tanzania", lat: -6.2220, lng: 39.2249 },
  { code: "EBB", name: "Entebbe International", city: "Entebbe", country: "Uganda", lat: 0.0424, lng: 32.4435 },
  { code: "KGL", name: "Kigali International", city: "Kigali", country: "Rwanda", lat: -1.9686, lng: 30.1395 },
  { code: "BJM", name: "Bujumbura International", city: "Bujumbura", country: "Burundi", lat: -3.3240, lng: 29.3185 },
  { code: "MGQ", name: "Aden Adde International", city: "Mogadishu", country: "Somalia", lat: 2.0144, lng: 45.3047 },
  { code: "DJI", name: "Djibouti-Ambouli International", city: "Djibouti", country: "Djibouti", lat: 11.5473, lng: 43.1595 },
  { code: "ASM", name: "Asmara International", city: "Asmara", country: "Eritrea", lat: 15.2919, lng: 38.9107 },
  { code: "SSZ", name: "Juba International", city: "Juba", country: "South Sudan", lat: 4.8720, lng: 31.6011 },
  { code: "MAL", name: "Malindi Airport", city: "Malindi", country: "Kenya", lat: -3.2293, lng: 40.1017 },

  // Southern Africa
  { code: "JNB", name: "OR Tambo International", city: "Johannesburg", country: "South Africa", lat: -26.1392, lng: 28.2460 },
  { code: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa", lat: -33.9648, lng: 18.6017 },
  { code: "DUR", name: "King Shaka International", city: "Durban", country: "South Africa", lat: -29.6144, lng: 31.1197 },
  { code: "PLZ", name: "Chief Dawid Stuurman International", city: "Port Elizabeth", country: "South Africa", lat: -33.9849, lng: 25.6173 },
  { code: "GRJ", name: "George Airport", city: "George", country: "South Africa", lat: -34.0056, lng: 22.3789 },
  { code: "ELS", name: "King Phalo Airport", city: "East London", country: "South Africa", lat: -32.9961, lng: 27.8259 },
  { code: "BFN", name: "Bram Fischer International", city: "Bloemfontein", country: "South Africa", lat: -29.0927, lng: 26.3024 },
  { code: "HRE", name: "Robert Gabriel Mugabe International", city: "Harare", country: "Zimbabwe", lat: -17.9318, lng: 31.0928 },
  { code: "BUQ", name: "Joshua Mqabuko Nkomo International", city: "Bulawayo", country: "Zimbabwe", lat: -20.0174, lng: 28.6179 },
  { code: "LUN", name: "Kenneth Kaunda International", city: "Lusaka", country: "Zambia", lat: -15.3308, lng: 28.4526 },
  { code: "NLA", name: "Simon Mwansa Kapwepwe International", city: "Ndola", country: "Zambia", lat: -12.9981, lng: 28.6649 },
  { code: "GBE", name: "Sir Seretse Khama International", city: "Gaborone", country: "Botswana", lat: -24.5552, lng: 25.9182 },
  { code: "MTS", name: "King Mswati III International", city: "Manzini", country: "Eswatini", lat: -26.3589, lng: 31.7099 },
  { code: "MSU", name: "Moshoeshoe I International", city: "Maseru", country: "Lesotho", lat: -29.4623, lng: 27.5525 },
  { code: "WDH", name: "Hosea Kutako International", city: "Windhoek", country: "Namibia", lat: -22.4799, lng: 17.4709 },
  { code: "TNR", name: "Ivato International", city: "Antananarivo", country: "Madagascar", lat: -18.7969, lng: 47.4788 },
  { code: "MRU", name: "Sir Seewoosagur Ramgoolam International", city: "Port Louis", country: "Mauritius", lat: -20.4302, lng: 57.6836 },
  { code: "SEZ", name: "Seychelles International", city: "Victoria", country: "Seychelles", lat: -4.6743, lng: 55.5218 },
  { code: "MPM", name: "Maputo International", city: "Maputo", country: "Mozambique", lat: -25.9208, lng: 32.5726 },
  { code: "BEW", name: "Beira Airport", city: "Beira", country: "Mozambique", lat: -19.7964, lng: 34.9076 },

  // North Africa
  { code: "CAI", name: "Cairo International", city: "Cairo", country: "Egypt", lat: 30.1219, lng: 31.4056 },
  { code: "HRG", name: "Hurghada International", city: "Hurghada", country: "Egypt", lat: 27.1783, lng: 33.7994 },
  { code: "SSH", name: "Sharm el-Sheikh International", city: "Sharm el-Sheikh", country: "Egypt", lat: 27.9773, lng: 34.3950 },
  { code: "LXR", name: "Luxor International", city: "Luxor", country: "Egypt", lat: 25.6710, lng: 32.7066 },
  { code: "ASW", name: "Aswan International", city: "Aswan", country: "Egypt", lat: 23.9644, lng: 32.8199 },
  { code: "ALY", name: "El Nouzha Airport", city: "Alexandria", country: "Egypt", lat: 31.1839, lng: 29.9489 },
  { code: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco", lat: 33.3675, lng: -7.5899 },
  { code: "RAK", name: "Marrakech Menara Airport", city: "Marrakech", country: "Morocco", lat: 31.6069, lng: -8.0363 },
  { code: "FEZ", name: "Fes-Saiss Airport", city: "Fes", country: "Morocco", lat: 33.9273, lng: -4.9779 },
  { code: "AGA", name: "Al Massira Airport", city: "Agadir", country: "Morocco", lat: 30.3250, lng: -9.4130 },
  { code: "TNG", name: "Ibn Battuta Airport", city: "Tangier", country: "Morocco", lat: 35.7269, lng: -5.9169 },
  { code: "RBA", name: "Rabat-Sale Airport", city: "Rabat", country: "Morocco", lat: 34.0515, lng: -6.7515 },
  { code: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "Algeria", lat: 36.6910, lng: 3.2154 },
  { code: "ORN", name: "Ahmed Ben Bella Airport", city: "Oran", country: "Algeria", lat: 35.6239, lng: -0.6212 },
  { code: "TUN", name: "Tunis-Carthage International", city: "Tunis", country: "Tunisia", lat: 36.8510, lng: 10.2272 },
  { code: "SFA", name: "Sfax-Thyna International", city: "Sfax", country: "Tunisia", lat: 34.7180, lng: 10.6910 },
  { code: "MIR", name: "Monastir Habib Bourguiba International", city: "Monastir", country: "Tunisia", lat: 35.7581, lng: 10.7547 },
  { code: "TBR", name: "Gabes Matmata International", city: "Gabes", country: "Tunisia", lat: 33.8789, lng: 10.1033 },
  { code: "TIP", name: "Mitiga International", city: "Tripoli", country: "Libya", lat: 32.8941, lng: 13.2760 },
  { code: "BEN", name: "Benina International", city: "Benghazi", country: "Libya", lat: 32.0968, lng: 20.2695 },
  { code: "KRT", name: "Khartoum International", city: "Khartoum", country: "Sudan", lat: 15.5895, lng: 32.5532 },

  // Middle East
  { code: "DXB", name: "Dubai International", city: "Dubai", country: "UAE", lat: 25.2528, lng: 55.3644 },
  { code: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "UAE", lat: 24.4330, lng: 54.6511 },
  { code: "SHJ", name: "Sharjah International", city: "Sharjah", country: "UAE", lat: 25.3286, lng: 55.5172 },
  { code: "RKT", name: "Ras Al Khaimah International", city: "Ras Al Khaimah", country: "UAE", lat: 25.6135, lng: 55.9388 },
  { code: "DOH", name: "Hamad International", city: "Doha", country: "Qatar", lat: 25.2609, lng: 51.6138 },
  { code: "BAH", name: "Bahrain International", city: "Manama", country: "Bahrain", lat: 26.2708, lng: 50.6336 },
  { code: "KWI", name: "Kuwait International", city: "Kuwait City", country: "Kuwait", lat: 29.2267, lng: 47.9689 },
  { code: "MCT", name: "Muscat International", city: "Muscat", country: "Oman", lat: 23.5933, lng: 58.2844 },
  { code: "SLL", name: "Salalah Airport", city: "Salalah", country: "Oman", lat: 17.0387, lng: 54.0913 },
  { code: "RUH", name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia", lat: 24.9576, lng: 46.6988 },
  { code: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia", lat: 21.6796, lng: 39.1565 },
  { code: "DMM", name: "King Fahd International", city: "Dammam", country: "Saudi Arabia", lat: 26.4712, lng: 49.7979 },
  { code: "MED", name: "Prince Mohammad bin Abdulaziz International", city: "Medina", country: "Saudi Arabia", lat: 24.5534, lng: 39.7051 },
  { code: "TIF", name: "Taif Regional Airport", city: "Taif", country: "Saudi Arabia", lat: 21.4834, lng: 40.5444 },
  { code: "AHB", name: "Abha Regional Airport", city: "Abha", country: "Saudi Arabia", lat: 18.2404, lng: 42.6566 },
  { code: "AMM", name: "Queen Alia International", city: "Amman", country: "Jordan", lat: 31.7226, lng: 35.9932 },
  { code: "AQJ", name: "King Hussein International", city: "Aqaba", country: "Jordan", lat: 29.6116, lng: 35.0181 },
  { code: "BEY", name: "Rafic Hariri International", city: "Beirut", country: "Lebanon", lat: 33.8209, lng: 35.4884 },
  { code: "DAM", name: "Damascus International", city: "Damascus", country: "Syria", lat: 33.4114, lng: 36.5156 },
  { code: "BGW", name: "Baghdad International", city: "Baghdad", country: "Iraq", lat: 33.2625, lng: 44.2346 },
  { code: "BSR", name: "Basra International", city: "Basra", country: "Iraq", lat: 30.5491, lng: 47.6621 },
  { code: "EBL", name: "Erbil International", city: "Erbil", country: "Iraq", lat: 36.2376, lng: 43.9632 },
  { code: "TLV", name: "Ben Gurion International", city: "Tel Aviv", country: "Israel", lat: 32.0114, lng: 34.8867 },
  { code: "HFA", name: "Haifa Airport", city: "Haifa", country: "Israel", lat: 32.8094, lng: 35.0431 },
  { code: "SAH", name: "Sanaa International", city: "Sanaa", country: "Yemen", lat: 15.4763, lng: 44.2197 },
  { code: "ADE", name: "Aden International", city: "Aden", country: "Yemen", lat: 12.8295, lng: 45.0288 },
  { code: "IKA", name: "Imam Khomeini International", city: "Tehran", country: "Iran", lat: 35.4161, lng: 51.1522 },
  { code: "THR", name: "Mehrabad International", city: "Tehran", country: "Iran", lat: 35.6892, lng: 51.3134 },
  { code: "MHD", name: "Mashhad International", city: "Mashhad", country: "Iran", lat: 36.2352, lng: 59.6400 },
  { code: "IFN", name: "Isfahan International", city: "Isfahan", country: "Iran", lat: 32.7508, lng: 51.8613 },
  { code: "SYZ", name: "Shiraz International", city: "Shiraz", country: "Iran", lat: 29.5392, lng: 52.5898 },
  { code: "TBZ", name: "Tabriz International", city: "Tabriz", country: "Iran", lat: 38.1339, lng: 46.2350 },

  // South Asia
  { code: "DEL", name: "Indira Gandhi International", city: "New Delhi", country: "India", lat: 28.5665, lng: 77.1031 },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India", lat: 19.0896, lng: 72.8656 },
  { code: "MAA", name: "Chennai International", city: "Chennai", country: "India", lat: 12.9900, lng: 80.1693 },
  { code: "BLR", name: "Kempegowda International", city: "Bangalore", country: "India", lat: 13.1986, lng: 77.7066 },
  { code: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "India", lat: 22.6547, lng: 88.4467 },
  { code: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "India", lat: 17.2403, lng: 78.4294 },
  { code: "COK", name: "Cochin International", city: "Kochi", country: "India", lat: 10.1520, lng: 76.4019 },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International", city: "Ahmedabad", country: "India", lat: 23.0772, lng: 72.6347 },
  { code: "PNQ", name: "Pune Airport", city: "Pune", country: "India", lat: 18.5822, lng: 73.9197 },
  { code: "GOI", name: "Goa International", city: "Goa", country: "India", lat: 15.3808, lng: 73.8314 },
  { code: "JAI", name: "Jaipur International", city: "Jaipur", country: "India", lat: 26.8242, lng: 75.8122 },
  { code: "LKO", name: "Chaudhary Charan Singh International", city: "Lucknow", country: "India", lat: 26.7606, lng: 80.8893 },
  { code: "VNS", name: "Lal Bahadur Shastri International", city: "Varanasi", country: "India", lat: 25.4524, lng: 82.8593 },
  { code: "PAT", name: "Jay Prakash Narayan International", city: "Patna", country: "India", lat: 25.5913, lng: 85.0880 },
  { code: "NAG", name: "Dr. Babasaheb Ambedkar International", city: "Nagpur", country: "India", lat: 21.0922, lng: 79.0472 },
  { code: "IXC", name: "Chandigarh International", city: "Chandigarh", country: "India", lat: 30.6735, lng: 76.7885 },
  { code: "ATQ", name: "Sri Guru Ram Dass Jee International", city: "Amritsar", country: "India", lat: 31.7096, lng: 74.7973 },
  { code: "SXR", name: "Sheikh ul-Alam International", city: "Srinagar", country: "India", lat: 34.0054, lng: 74.7742 },
  { code: "TRV", name: "Trivandrum International", city: "Thiruvananthapuram", country: "India", lat: 8.4812, lng: 76.9201 },
  { code: "IXB", name: "Bagdogra Airport", city: "Siliguri", country: "India", lat: 26.6812, lng: 88.3286 },
  { code: "GAU", name: "Lokpriya Gopinath Bordoloi International", city: "Guwahati", country: "India", lat: 26.1061, lng: 91.5859 },
  { code: "ISB", name: "New Islamabad International", city: "Islamabad", country: "Pakistan", lat: 33.5607, lng: 72.8516 },
  { code: "KHI", name: "Jinnah International", city: "Karachi", country: "Pakistan", lat: 24.9065, lng: 67.1608 },
  { code: "LHE", name: "Allama Iqbal International", city: "Lahore", country: "Pakistan", lat: 31.5216, lng: 74.4036 },
  { code: "PEW", name: "Bacha Khan International", city: "Peshawar", country: "Pakistan", lat: 33.9939, lng: 71.5146 },
  { code: "MUX", name: "Multan International", city: "Multan", country: "Pakistan", lat: 30.2032, lng: 71.4192 },
  { code: "SKT", name: "Sialkot International", city: "Sialkot", country: "Pakistan", lat: 32.5356, lng: 74.3639 },
  { code: "DAC", name: "Hazrat Shahjalal International", city: "Dhaka", country: "Bangladesh", lat: 23.8433, lng: 90.3978 },
  { code: "CGP", name: "Shah Amanat International", city: "Chittagong", country: "Bangladesh", lat: 22.2496, lng: 91.8133 },
  { code: "CMB", name: "Bandaranaike International", city: "Colombo", country: "Sri Lanka", lat: 7.1808, lng: 79.8841 },
  { code: "KTM", name: "Tribhuvan International", city: "Kathmandu", country: "Nepal", lat: 27.6966, lng: 85.3591 },
  { code: "PBH", name: "Paro Airport", city: "Paro", country: "Bhutan", lat: 27.4033, lng: 89.4246 },
  { code: "MLE", name: "Velana International", city: "Male", country: "Maldives", lat: 4.1918, lng: 73.5290 },

  // Southeast Asia
  { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore", lat: 1.3644, lng: 103.9915 },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia", lat: 2.7456, lng: 101.7099 },
  { code: "JHB", name: "Senai International", city: "Johor Bahru", country: "Malaysia", lat: 1.6413, lng: 103.6698 },
  { code: "PEN", name: "Penang International", city: "Penang", country: "Malaysia", lat: 5.2977, lng: 100.2768 },
  { code: "BKI", name: "Kota Kinabalu International", city: "Kota Kinabalu", country: "Malaysia", lat: 5.9372, lng: 116.0508 },
  { code: "KCH", name: "Kuching International", city: "Kuching", country: "Malaysia", lat: 1.4847, lng: 110.3469 },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand", lat: 13.6811, lng: 100.7472 },
  { code: "DMK", name: "Don Mueang International", city: "Bangkok", country: "Thailand", lat: 13.9126, lng: 100.6067 },
  { code: "HKT", name: "Phuket International", city: "Phuket", country: "Thailand", lat: 8.1132, lng: 98.3169 },
  { code: "CNX", name: "Chiang Mai International", city: "Chiang Mai", country: "Thailand", lat: 18.7668, lng: 98.9628 },
  { code: "USM", name: "Samui Airport", city: "Ko Samui", country: "Thailand", lat: 9.5478, lng: 100.0627 },
  { code: "HDY", name: "Hat Yai International", city: "Hat Yai", country: "Thailand", lat: 6.9332, lng: 100.3930 },
  { code: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "Vietnam", lat: 10.8188, lng: 106.6520 },
  { code: "HAN", name: "Noi Bai International", city: "Hanoi", country: "Vietnam", lat: 21.2212, lng: 105.8072 },
  { code: "DAD", name: "Da Nang International", city: "Da Nang", country: "Vietnam", lat: 16.0439, lng: 108.1993 },
  { code: "HPH", name: "Cat Bi International", city: "Hai Phong", country: "Vietnam", lat: 20.8194, lng: 106.7248 },
  { code: "CXR", name: "Cam Ranh International", city: "Nha Trang", country: "Vietnam", lat: 11.9982, lng: 109.2194 },
  { code: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines", lat: 14.5086, lng: 121.0194 },
  { code: "CEB", name: "Mactan-Cebu International", city: "Cebu", country: "Philippines", lat: 10.3075, lng: 123.9790 },
  { code: "DVO", name: "Francisco Bangoy International", city: "Davao", country: "Philippines", lat: 7.1255, lng: 125.6458 },
  { code: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "Indonesia", lat: -6.1256, lng: 106.6558 },
  { code: "DPS", name: "Ngurah Rai International", city: "Bali", country: "Indonesia", lat: -8.7482, lng: 115.1672 },
  { code: "SUB", name: "Juanda International", city: "Surabaya", country: "Indonesia", lat: -7.3798, lng: 112.7870 },
  { code: "UPG", name: "Sultan Hasanuddin International", city: "Makassar", country: "Indonesia", lat: -5.0616, lng: 119.5540 },
  { code: "MDC", name: "Sam Ratulangi International", city: "Manado", country: "Indonesia", lat: 1.5493, lng: 124.9260 },
  { code: "BDO", name: "Husein Sastranegara International", city: "Bandung", country: "Indonesia", lat: -6.9006, lng: 107.5763 },
  { code: "RGN", name: "Yangon International", city: "Yangon", country: "Myanmar", lat: 16.9073, lng: 96.1332 },
  { code: "MDL", name: "Mandalay International", city: "Mandalay", country: "Myanmar", lat: 21.7022, lng: 95.9779 },
  { code: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "Cambodia", lat: 11.5466, lng: 104.8440 },
  { code: "REP", name: "Siem Reap International", city: "Siem Reap", country: "Cambodia", lat: 13.4107, lng: 103.8129 },
  { code: "VTE", name: "Wattay International", city: "Vientiane", country: "Laos", lat: 17.9883, lng: 102.5633 },
  { code: "LPQ", name: "Luang Prabang International", city: "Luang Prabang", country: "Laos", lat: 19.8973, lng: 102.1614 },
  { code: "BWN", name: "Brunei International", city: "Bandar Seri Begawan", country: "Brunei", lat: 4.9442, lng: 114.9283 },
  { code: "DRW", name: "Darwin International", city: "Darwin", country: "Australia", lat: -12.4147, lng: 130.8766 },
  { code: "DIL", name: "Presidente Nicolau Lobato International", city: "Dili", country: "Timor-Leste", lat: -8.5464, lng: 125.5247 },

  // East Asia
  { code: "PEK", name: "Beijing Capital International", city: "Beijing", country: "China", lat: 40.0799, lng: 116.6031 },
  { code: "PKX", name: "Beijing Daxing International", city: "Beijing", country: "China", lat: 39.5098, lng: 116.4105 },
  { code: "PVG", name: "Shanghai Pudong International", city: "Shanghai", country: "China", lat: 31.1434, lng: 121.8052 },
  { code: "SHA", name: "Shanghai Hongqiao International", city: "Shanghai", country: "China", lat: 31.1979, lng: 121.3363 },
  { code: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "China", lat: 23.3924, lng: 113.2988 },
  { code: "CTU", name: "Chengdu Tianfu International", city: "Chengdu", country: "China", lat: 30.3124, lng: 104.4440 },
  { code: "SZX", name: "Shenzhen Bao'an International", city: "Shenzhen", country: "China", lat: 22.6393, lng: 113.8107 },
  { code: "KMG", name: "Kunming Changshui International", city: "Kunming", country: "China", lat: 24.9920, lng: 102.7435 },
  { code: "WUH", name: "Wuhan Tianhe International", city: "Wuhan", country: "China", lat: 30.7838, lng: 114.2081 },
  { code: "XIY", name: "Xi'an Xianyang International", city: "Xi'an", country: "China", lat: 34.4471, lng: 108.7516 },
  { code: "HGH", name: "Hangzhou Xiaoshan International", city: "Hangzhou", country: "China", lat: 30.2295, lng: 120.4346 },
  { code: "NKG", name: "Nanjing Lukou International", city: "Nanjing", country: "China", lat: 31.7420, lng: 118.8620 },
  { code: "CKG", name: "Chongqing Jiangbei International", city: "Chongqing", country: "China", lat: 29.7192, lng: 106.6417 },
  { code: "CSX", name: "Changsha Huanghua International", city: "Changsha", country: "China", lat: 28.1892, lng: 113.2196 },
  { code: "TSN", name: "Tianjin Binhai International", city: "Tianjin", country: "China", lat: 39.1244, lng: 117.3462 },
  { code: "HRB", name: "Harbin Taiping International", city: "Harbin", country: "China", lat: 45.6234, lng: 126.2500 },
  { code: "TAO", name: "Qingdao Jiaodong International", city: "Qingdao", country: "China", lat: 36.3661, lng: 120.0849 },
  { code: "URC", name: "Urumqi Diwopu International", city: "Urumqi", country: "China", lat: 43.9071, lng: 87.4742 },
  { code: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "Hong Kong", lat: 22.3080, lng: 113.9185 },
  { code: "MFM", name: "Macau International", city: "Macau", country: "Macau", lat: 22.1496, lng: 113.5916 },
  { code: "TPE", name: "Taiwan Taoyuan International", city: "Taipei", country: "Taiwan", lat: 25.0777, lng: 121.2328 },
  { code: "TSA", name: "Taipei Songshan Airport", city: "Taipei", country: "Taiwan", lat: 25.0694, lng: 121.5522 },
  { code: "KHH", name: "Kaohsiung International", city: "Kaohsiung", country: "Taiwan", lat: 22.5771, lng: 120.3500 },
  { code: "ICN", name: "Incheon International", city: "Seoul", country: "South Korea", lat: 37.4602, lng: 126.4407 },
  { code: "GMP", name: "Gimpo International", city: "Seoul", country: "South Korea", lat: 37.5583, lng: 126.7906 },
  { code: "PUS", name: "Gimhae International", city: "Busan", country: "South Korea", lat: 35.1795, lng: 128.9382 },
  { code: "CJU", name: "Jeju International", city: "Jeju", country: "South Korea", lat: 33.5113, lng: 126.4930 },
  { code: "NRT", name: "Narita International", city: "Tokyo", country: "Japan", lat: 35.7647, lng: 140.3864 },
  { code: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan", lat: 35.5494, lng: 139.7798 },
  { code: "KIX", name: "Kansai International", city: "Osaka", country: "Japan", lat: 34.4347, lng: 135.2440 },
  { code: "ITM", name: "Itami Airport", city: "Osaka", country: "Japan", lat: 34.7855, lng: 135.4380 },
  { code: "NGO", name: "Chubu Centrair International", city: "Nagoya", country: "Japan", lat: 34.8583, lng: 136.8050 },
  { code: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "Japan", lat: 42.7752, lng: 141.6922 },
  { code: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan", lat: 33.5859, lng: 130.4511 },
  { code: "OKA", name: "Naha Airport", city: "Okinawa", country: "Japan", lat: 26.1958, lng: 127.6464 },
  { code: "HIJ", name: "Hiroshima Airport", city: "Hiroshima", country: "Japan", lat: 34.4361, lng: 132.9194 },
  { code: "ULN", name: "Chinggis Khaan International", city: "Ulaanbaatar", country: "Mongolia", lat: 47.8431, lng: 106.7664 },

  // Central Asia
  { code: "ALA", name: "Almaty International", city: "Almaty", country: "Kazakhstan", lat: 43.3521, lng: 77.0405 },
  { code: "NQZ", name: "Nursultan Nazarbayev International", city: "Astana", country: "Kazakhstan", lat: 51.0222, lng: 71.4669 },
  { code: "TAS", name: "Islam Karimov Tashkent International", city: "Tashkent", country: "Uzbekistan", lat: 41.2579, lng: 69.2812 },
  { code: "SKD", name: "Samarkand International", city: "Samarkand", country: "Uzbekistan", lat: 39.7005, lng: 66.9838 },
  { code: "FRU", name: "Manas International", city: "Bishkek", country: "Kyrgyzstan", lat: 43.0613, lng: 74.4777 },
  { code: "ASB", name: "Ashgabat International", city: "Ashgabat", country: "Turkmenistan", lat: 37.9868, lng: 58.3610 },
  { code: "DYU", name: "Dushanbe International", city: "Dushanbe", country: "Tajikistan", lat: 38.5433, lng: 68.8250 },
  { code: "KBL", name: "Hamid Karzai International", city: "Kabul", country: "Afghanistan", lat: 34.5659, lng: 69.2123 },

  // Europe - Western
  { code: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom", lat: 51.4775, lng: -0.4614 },
  { code: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom", lat: 51.1537, lng: -0.1821 },
  { code: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom", lat: 51.8850, lng: 0.2350 },
  { code: "LTN", name: "Luton Airport", city: "London", country: "United Kingdom", lat: 51.8747, lng: -0.3683 },
  { code: "LCY", name: "London City Airport", city: "London", country: "United Kingdom", lat: 51.5048, lng: 0.0552 },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", lat: 53.3537, lng: -2.2750 },
  { code: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom", lat: 52.4539, lng: -1.7480 },
  { code: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom", lat: 55.8719, lng: -4.4331 },
  { code: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", lat: 55.9500, lng: -3.3725 },
  { code: "BRS", name: "Bristol Airport", city: "Bristol", country: "United Kingdom", lat: 51.3827, lng: -2.7191 },
  { code: "NCL", name: "Newcastle Airport", city: "Newcastle", country: "United Kingdom", lat: 55.0375, lng: -1.6917 },
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France", lat: 49.0097, lng: 2.5479 },
  { code: "ORY", name: "Orly Airport", city: "Paris", country: "France", lat: 48.7233, lng: 2.3794 },
  { code: "NCE", name: "Nice Cote d'Azur Airport", city: "Nice", country: "France", lat: 43.6584, lng: 7.2159 },
  { code: "LYS", name: "Lyon Saint-Exupery Airport", city: "Lyon", country: "France", lat: 45.7256, lng: 5.0811 },
  { code: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France", lat: 43.4393, lng: 5.2214 },
  { code: "TLS", name: "Toulouse Blagnac Airport", city: "Toulouse", country: "France", lat: 43.6293, lng: 1.3638 },
  { code: "BOD", name: "Bordeaux-Merignac Airport", city: "Bordeaux", country: "France", lat: 44.8283, lng: -0.7156 },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", lat: 50.0379, lng: 8.5622 },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany", lat: 48.3537, lng: 11.7750 },
  { code: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany", lat: 52.3667, lng: 13.5033 },
  { code: "DUS", name: "Dusseldorf Airport", city: "Dusseldorf", country: "Germany", lat: 51.2895, lng: 6.7668 },
  { code: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany", lat: 53.6304, lng: 9.9882 },
  { code: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany", lat: 50.8659, lng: 7.1427 },
  { code: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany", lat: 48.6899, lng: 9.2220 },
  { code: "NUE", name: "Nuremberg Airport", city: "Nuremberg", country: "Germany", lat: 49.4987, lng: 11.0669 },
  { code: "AMS", name: "Amsterdam Schiphol Airport", city: "Amsterdam", country: "Netherlands", lat: 52.3086, lng: 4.7639 },
  { code: "EIN", name: "Eindhoven Airport", city: "Eindhoven", country: "Netherlands", lat: 51.4501, lng: 5.3746 },
  { code: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium", lat: 50.9014, lng: 4.4844 },
  { code: "CRL", name: "Brussels South Charleroi Airport", city: "Charleroi", country: "Belgium", lat: 50.4592, lng: 4.4538 },
  { code: "LUX", name: "Luxembourg Airport", city: "Luxembourg City", country: "Luxembourg", lat: 49.6233, lng: 6.2044 },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", lat: 47.4647, lng: 8.5492 },
  { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland", lat: 46.2370, lng: 6.1089 },
  { code: "BSL", name: "EuroAirport Basel Mulhouse Freiburg", city: "Basel", country: "Switzerland", lat: 47.5896, lng: 7.5299 },
  { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria", lat: 48.1102, lng: 16.5697 },
  { code: "SZG", name: "Salzburg Airport", city: "Salzburg", country: "Austria", lat: 47.7933, lng: 13.0043 },
  { code: "INN", name: "Innsbruck Airport", city: "Innsbruck", country: "Austria", lat: 47.2602, lng: 11.3440 },

  // Europe - Southern
  { code: "MAD", name: "Adolfo Suarez Madrid-Barajas Airport", city: "Madrid", country: "Spain", lat: 40.4719, lng: -3.5626 },
  { code: "BCN", name: "Barcelona El Prat Airport", city: "Barcelona", country: "Spain", lat: 41.2971, lng: 2.0785 },
  { code: "PMI", name: "Palma de Mallorca Airport", city: "Palma", country: "Spain", lat: 39.5517, lng: 2.7388 },
  { code: "AGP", name: "Malaga Airport", city: "Malaga", country: "Spain", lat: 36.6749, lng: -4.4991 },
  { code: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain", lat: 39.4893, lng: -0.4816 },
  { code: "SVQ", name: "Sevilla Airport", city: "Seville", country: "Spain", lat: 37.4180, lng: -5.8931 },
  { code: "BIO", name: "Bilbao Airport", city: "Bilbao", country: "Spain", lat: 43.3011, lng: -2.9106 },
  { code: "LIS", name: "Lisbon Humberto Delgado Airport", city: "Lisbon", country: "Portugal", lat: 38.7813, lng: -9.1359 },
  { code: "OPO", name: "Francisco Sa Carneiro Airport", city: "Porto", country: "Portugal", lat: 41.2481, lng: -8.6814 },
  { code: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal", lat: 37.0144, lng: -7.9659 },
  { code: "FCO", name: "Leonardo da Vinci International", city: "Rome", country: "Italy", lat: 41.8003, lng: 12.2389 },
  { code: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy", lat: 45.6306, lng: 8.7281 },
  { code: "LIN", name: "Milan Linate Airport", city: "Milan", country: "Italy", lat: 45.4453, lng: 9.2767 },
  { code: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "Italy", lat: 45.5053, lng: 12.3519 },
  { code: "NAP", name: "Naples International Airport", city: "Naples", country: "Italy", lat: 40.8860, lng: 14.2908 },
  { code: "BLQ", name: "Bologna Guglielmo Marconi Airport", city: "Bologna", country: "Italy", lat: 44.5354, lng: 11.2887 },
  { code: "PMO", name: "Falcone Borsellino Airport", city: "Palermo", country: "Italy", lat: 38.1759, lng: 13.0910 },
  { code: "CTA", name: "Catania Fontanarossa Airport", city: "Catania", country: "Italy", lat: 37.4668, lng: 15.0664 },
  { code: "FLR", name: "Florence Peretola Airport", city: "Florence", country: "Italy", lat: 43.8099, lng: 11.2051 },
  { code: "ATH", name: "Athens International Eleftherios Venizelos", city: "Athens", country: "Greece", lat: 37.9364, lng: 23.9445 },
  { code: "SKG", name: "Thessaloniki Macedonia Airport", city: "Thessaloniki", country: "Greece", lat: 40.5197, lng: 22.9709 },
  { code: "HER", name: "Heraklion International Nikos Kazantzakis", city: "Heraklion", country: "Greece", lat: 35.3397, lng: 25.1803 },
  { code: "RHO", name: "Rhodes Diagoras Airport", city: "Rhodes", country: "Greece", lat: 36.4054, lng: 28.0862 },
  { code: "CFU", name: "Corfu International Airport", city: "Corfu", country: "Greece", lat: 39.6019, lng: 19.9117 },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", lat: 41.2608, lng: 28.7418 },
  { code: "SAW", name: "Sabiha Gokcen International", city: "Istanbul", country: "Turkey", lat: 40.8986, lng: 29.3092 },
  { code: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey", lat: 36.8987, lng: 30.8005 },
  { code: "ADB", name: "Adnan Menderes Airport", city: "Izmir", country: "Turkey", lat: 38.2924, lng: 27.1570 },
  { code: "ESB", name: "Esenboga International", city: "Ankara", country: "Turkey", lat: 40.1281, lng: 32.9951 },
  { code: "DLM", name: "Dalaman Airport", city: "Dalaman", country: "Turkey", lat: 36.7130, lng: 28.7925 },
  { code: "BJV", name: "Milas Bodrum Airport", city: "Bodrum", country: "Turkey", lat: 37.2501, lng: 27.6643 },
  { code: "ADA", name: "Adana Sakirpasa Airport", city: "Adana", country: "Turkey", lat: 36.9822, lng: 35.2804 },
  { code: "TZX", name: "Trabzon Airport", city: "Trabzon", country: "Turkey", lat: 40.9952, lng: 39.7897 },

  // Europe - Northern
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark", lat: 55.6180, lng: 12.6560 },
  { code: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "Norway", lat: 60.1939, lng: 11.1004 },
  { code: "BGO", name: "Bergen Airport Flesland", city: "Bergen", country: "Norway", lat: 60.2934, lng: 5.2181 },
  { code: "TRD", name: "Trondheim Airport Vaernes", city: "Trondheim", country: "Norway", lat: 63.4578, lng: 10.9239 },
  { code: "SVG", name: "Stavanger Airport Sola", city: "Stavanger", country: "Norway", lat: 58.8767, lng: 5.6378 },
  { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden", lat: 59.6519, lng: 17.9186 },
  { code: "NYO", name: "Stockholm Skavsta Airport", city: "Stockholm", country: "Sweden", lat: 58.7886, lng: 16.9122 },
  { code: "GOT", name: "Gothenburg Landvetter Airport", city: "Gothenburg", country: "Sweden", lat: 57.6628, lng: 12.2798 },
  { code: "MMX", name: "Malmoe Airport", city: "Malmo", country: "Sweden", lat: 55.5363, lng: 13.3762 },
  { code: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "Finland", lat: 60.3172, lng: 24.9633 },
  { code: "OUL", name: "Oulu Airport", city: "Oulu", country: "Finland", lat: 64.9301, lng: 25.3546 },
  { code: "TMP", name: "Tampere-Pirkkala Airport", city: "Tampere", country: "Finland", lat: 61.4141, lng: 23.6044 },
  { code: "KEF", name: "Keflavik International Airport", city: "Reykjavik", country: "Iceland", lat: 63.9850, lng: -22.6056 },

  // Europe - Eastern
  { code: "SVO", name: "Sheremetyevo International Airport", city: "Moscow", country: "Russia", lat: 55.9726, lng: 37.4146 },
  { code: "DME", name: "Domodedovo International Airport", city: "Moscow", country: "Russia", lat: 55.4088, lng: 37.9063 },
  { code: "VKO", name: "Vnukovo International Airport", city: "Moscow", country: "Russia", lat: 55.5915, lng: 37.2615 },
  { code: "LED", name: "Pulkovo Airport", city: "St. Petersburg", country: "Russia", lat: 59.8003, lng: 30.2625 },
  { code: "KZN", name: "Kazan International Airport", city: "Kazan", country: "Russia", lat: 55.6063, lng: 49.2787 },
  { code: "SVX", name: "Koltsovo Airport", city: "Yekaterinburg", country: "Russia", lat: 56.7431, lng: 60.8027 },
  { code: "OVB", name: "Novosibirsk Tolmachevo Airport", city: "Novosibirsk", country: "Russia", lat: 54.9963, lng: 82.6507 },
  { code: "KRR", name: "Pashkovsky Airport", city: "Krasnodar", country: "Russia", lat: 45.0346, lng: 39.1705 },
  { code: "AER", name: "Sochi International Airport", city: "Sochi", country: "Russia", lat: 43.4499, lng: 39.9566 },
  { code: "ROV", name: "Platov International Airport", city: "Rostov-on-Don", country: "Russia", lat: 47.4938, lng: 39.9247 },
  { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland", lat: 52.1657, lng: 20.9671 },
  { code: "KRK", name: "Krakow John Paul II Airport", city: "Krakow", country: "Poland", lat: 50.0777, lng: 19.7848 },
  { code: "GDN", name: "Gdansk Lech Walesa Airport", city: "Gdansk", country: "Poland", lat: 54.3776, lng: 18.4662 },
  { code: "WRO", name: "Wroclaw Copernicus Airport", city: "Wroclaw", country: "Poland", lat: 51.1027, lng: 16.8858 },
  { code: "KTW", name: "Katowice International Airport", city: "Katowice", country: "Poland", lat: 50.4743, lng: 19.0800 },
  { code: "PRG", name: "Vaclav Havel Airport Prague", city: "Prague", country: "Czech Republic", lat: 50.1008, lng: 14.2600 },
  { code: "BTS", name: "Milan Rastislav Stefanik Airport", city: "Bratislava", country: "Slovakia", lat: 48.1702, lng: 17.2127 },
  { code: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "Hungary", lat: 47.4298, lng: 19.2611 },
  { code: "OTP", name: "Henri Coanda International Airport", city: "Bucharest", country: "Romania", lat: 44.5711, lng: 26.0858 },
  { code: "CLJ", name: "Cluj-Napoca International Airport", city: "Cluj-Napoca", country: "Romania", lat: 46.7852, lng: 23.6862 },
  { code: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria", lat: 42.6952, lng: 23.4114 },
  { code: "VAR", name: "Varna Airport", city: "Varna", country: "Bulgaria", lat: 43.2321, lng: 27.8251 },
  { code: "LJU", name: "Ljubljana Joze Pucnik Airport", city: "Ljubljana", country: "Slovenia", lat: 46.2237, lng: 14.4576 },
  { code: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "Croatia", lat: 45.7429, lng: 16.0688 },
  { code: "SPU", name: "Split Airport", city: "Split", country: "Croatia", lat: 43.5389, lng: 16.2980 },
  { code: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia", lat: 42.5614, lng: 18.2682 },
  { code: "SJJ", name: "Sarajevo International Airport", city: "Sarajevo", country: "Bosnia and Herzegovina", lat: 43.8246, lng: 18.3315 },
  { code: "SKP", name: "Skopje International Airport", city: "Skopje", country: "North Macedonia", lat: 41.9616, lng: 21.6214 },
  { code: "TIA", name: "Tirana International Airport Nene Tereza", city: "Tirana", country: "Albania", lat: 41.4147, lng: 19.7206 },
  { code: "POD", name: "Podgorica Airport", city: "Podgorica", country: "Montenegro", lat: 42.3594, lng: 19.2519 },
  { code: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia", lat: 44.8184, lng: 20.3091 },
  { code: "KIV", name: "Chisinau International Airport", city: "Chisinau", country: "Moldova", lat: 46.9277, lng: 28.9313 },
  { code: "KBP", name: "Kyiv Boryspil International Airport", city: "Kyiv", country: "Ukraine", lat: 50.3450, lng: 30.8947 },
  { code: "LWO", name: "Lviv Danylo Halytskyi International Airport", city: "Lviv", country: "Ukraine", lat: 49.8125, lng: 23.9561 },
  { code: "TBS", name: "Tbilisi International Airport", city: "Tbilisi", country: "Georgia", lat: 41.6693, lng: 44.9547 },
  { code: "EVN", name: "Zvartnots International Airport", city: "Yerevan", country: "Armenia", lat: 40.1473, lng: 44.3959 },
  { code: "GYD", name: "Heydar Aliyev International Airport", city: "Baku", country: "Azerbaijan", lat: 40.4675, lng: 50.0467 },
  { code: "RIX", name: "Riga International Airport", city: "Riga", country: "Latvia", lat: 56.9236, lng: 23.9711 },
  { code: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania", lat: 54.6341, lng: 25.2858 },
  { code: "TLL", name: "Lennart Meri Tallinn Airport", city: "Tallinn", country: "Estonia", lat: 59.4133, lng: 24.8328 },
  { code: "MSQ", name: "Minsk National Airport", city: "Minsk", country: "Belarus", lat: 53.8825, lng: 28.0307 },

  // North America - USA
  { code: "AEX", name: "Alexandria International", city: "Alexandria", country: "United States", lat: 31.3274, lng: -92.5498 },
  { code: "AMA", name: "Rick Husband Amarillo International", city: "Amarillo", country: "United States", lat: 35.2194, lng: -101.7059 },
  { code: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "United States", lat: 33.6407, lng: -84.4277 },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "United States", lat: 33.9425, lng: -118.4081 },
  { code: "ORD", name: "O'Hare International", city: "Chicago", country: "United States", lat: 41.9742, lng: -87.9073 },
  { code: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "United States", lat: 32.8998, lng: -97.0403 },
  { code: "DEN", name: "Denver International", city: "Denver", country: "United States", lat: 39.8561, lng: -104.6737 },
  { code: "JFK", name: "John F. Kennedy International", city: "New York", country: "United States", lat: 40.6413, lng: -73.7781 },
  { code: "SFO", name: "San Francisco International", city: "San Francisco", country: "United States", lat: 37.6213, lng: -122.3790 },
  { code: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "United States", lat: 47.4502, lng: -122.3088 },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "United States", lat: 36.0840, lng: -115.1537 },
  { code: "MCO", name: "Orlando International", city: "Orlando", country: "United States", lat: 28.4294, lng: -81.3089 },
  { code: "EWR", name: "Newark Liberty International", city: "Newark", country: "United States", lat: 40.6925, lng: -74.1687 },
  { code: "MIA", name: "Miami International", city: "Miami", country: "United States", lat: 25.7959, lng: -80.2870 },
  { code: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "United States", lat: 35.2140, lng: -80.9431 },
  { code: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "United States", lat: 33.4373, lng: -112.0078 },
  { code: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "United States", lat: 29.9902, lng: -95.3368 },
  { code: "BOS", name: "Boston Logan International", city: "Boston", country: "United States", lat: 42.3656, lng: -71.0096 },
  { code: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "United States", lat: 44.8848, lng: -93.2223 },
  { code: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "United States", lat: 42.2162, lng: -83.3554 },
  { code: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "United States", lat: 26.0726, lng: -80.1527 },
  { code: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "United States", lat: 39.8719, lng: -75.2411 },
  { code: "BWI", name: "Baltimore/Washington International Thurgood Marshall", city: "Baltimore", country: "United States", lat: 39.1754, lng: -76.6683 },
  { code: "DCA", name: "Ronald Reagan Washington National", city: "Washington D.C.", country: "United States", lat: 38.8521, lng: -77.0377 },
  { code: "IAD", name: "Washington Dulles International", city: "Washington D.C.", country: "United States", lat: 38.9531, lng: -77.4565 },
  { code: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "United States", lat: 40.7884, lng: -111.9778 },
  { code: "SAN", name: "San Diego International", city: "San Diego", country: "United States", lat: 32.7338, lng: -117.1933 },
  { code: "TPA", name: "Tampa International", city: "Tampa", country: "United States", lat: 27.9755, lng: -82.5332 },
  { code: "PDX", name: "Portland International", city: "Portland", country: "United States", lat: 45.5898, lng: -122.5951 },
  { code: "STL", name: "St. Louis Lambert International", city: "St. Louis", country: "United States", lat: 38.7487, lng: -90.3700 },
  { code: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "United States", lat: 21.3187, lng: -157.9225 },
  { code: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "United States", lat: 30.1975, lng: -97.6664 },
  { code: "BNA", name: "Nashville International", city: "Nashville", country: "United States", lat: 36.1245, lng: -86.6782 },
  { code: "MDW", name: "Chicago Midway International", city: "Chicago", country: "United States", lat: 41.7868, lng: -87.7522 },
  { code: "MCI", name: "Kansas City International", city: "Kansas City", country: "United States", lat: 39.2976, lng: -94.7139 },
  { code: "RDU", name: "Raleigh-Durham International", city: "Raleigh", country: "United States", lat: 35.8776, lng: -78.7875 },
  { code: "SAT", name: "San Antonio International", city: "San Antonio", country: "United States", lat: 29.5337, lng: -98.4698 },
  { code: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "United States", lat: 29.9934, lng: -90.2580 },
  { code: "SJC", name: "Norman Y. Mineta San Jose International", city: "San Jose", country: "United States", lat: 37.3626, lng: -121.9290 },
  { code: "OAK", name: "Oakland International", city: "Oakland", country: "United States", lat: 37.7213, lng: -122.2208 },
  { code: "SMF", name: "Sacramento International", city: "Sacramento", country: "United States", lat: 38.6954, lng: -121.5908 },
  { code: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", country: "United States", lat: 35.0402, lng: -106.6090 },
  { code: "MEM", name: "Memphis International", city: "Memphis", country: "United States", lat: 35.0424, lng: -89.9767 },
  { code: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "United States", lat: 40.4915, lng: -80.2329 },
  { code: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", country: "United States", lat: 41.4117, lng: -81.8498 },
  { code: "CVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", country: "United States", lat: 39.0488, lng: -84.6678 },
  { code: "IND", name: "Indianapolis International", city: "Indianapolis", country: "United States", lat: 39.7173, lng: -86.2944 },
  { code: "CMH", name: "John Glenn Columbus International", city: "Columbus", country: "United States", lat: 39.9980, lng: -82.8919 },
  { code: "BUF", name: "Buffalo Niagara International", city: "Buffalo", country: "United States", lat: 42.9405, lng: -78.7322 },
  { code: "JAX", name: "Jacksonville International", city: "Jacksonville", country: "United States", lat: 30.4941, lng: -81.6879 },
  { code: "RSW", name: "Southwest Florida International", city: "Fort Myers", country: "United States", lat: 26.5362, lng: -81.7552 },
  { code: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "United States", lat: 61.1741, lng: -149.9961 },

  // Canada
  { code: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "Canada", lat: 43.6777, lng: -79.6248 },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada", lat: 49.1947, lng: -123.1839 },
  { code: "YUL", name: "Montreal Trudeau International", city: "Montreal", country: "Canada", lat: 45.4706, lng: -73.7408 },
  { code: "YYC", name: "Calgary International", city: "Calgary", country: "Canada", lat: 51.1315, lng: -114.0106 },
  { code: "YEG", name: "Edmonton International", city: "Edmonton", country: "Canada", lat: 53.3097, lng: -113.5800 },
  { code: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", country: "Canada", lat: 45.3225, lng: -75.6692 },
  { code: "YHZ", name: "Halifax Stanfield International", city: "Halifax", country: "Canada", lat: 44.8808, lng: -63.5086 },
  { code: "YWG", name: "Winnipeg James Armstrong Richardson International", city: "Winnipeg", country: "Canada", lat: 49.9100, lng: -97.2398 },
  { code: "YQB", name: "Quebec City Jean Lesage International", city: "Quebec City", country: "Canada", lat: 46.7911, lng: -71.3933 },
  { code: "YXE", name: "Saskatoon John G. Diefenbaker International", city: "Saskatoon", country: "Canada", lat: 52.1708, lng: -106.6997 },

  // Mexico & Central America
  { code: "MEX", name: "Benito Juarez International", city: "Mexico City", country: "Mexico", lat: 19.4363, lng: -99.0721 },
  { code: "CUN", name: "Cancun International", city: "Cancun", country: "Mexico", lat: 21.0365, lng: -86.8771 },
  { code: "GDL", name: "Miguel Hidalgo y Costilla International", city: "Guadalajara", country: "Mexico", lat: 20.5218, lng: -103.3111 },
  { code: "MTY", name: "General Mariano Escobedo International", city: "Monterrey", country: "Mexico", lat: 25.7785, lng: -100.1069 },
  { code: "TIJ", name: "General Abelardo L. Rodriguez International", city: "Tijuana", country: "Mexico", lat: 32.5411, lng: -116.9700 },
  { code: "PVR", name: "Licenciado Gustavo Diaz Ordaz International", city: "Puerto Vallarta", country: "Mexico", lat: 20.6801, lng: -105.2544 },
  { code: "SJD", name: "Los Cabos International", city: "Los Cabos", country: "Mexico", lat: 23.1518, lng: -109.7216 },
  { code: "OAX", name: "Xoxocotlan International", city: "Oaxaca", country: "Mexico", lat: 16.9999, lng: -96.7266 },
  { code: "MID", name: "Manuel Crescencio Rejon International", city: "Merida", country: "Mexico", lat: 20.9370, lng: -89.6577 },
  { code: "GUA", name: "La Aurora International", city: "Guatemala City", country: "Guatemala", lat: 14.5833, lng: -90.5275 },
  { code: "SAP", name: "Ramon Villeda Morales International", city: "San Pedro Sula", country: "Honduras", lat: 15.4526, lng: -87.9236 },
  { code: "SAL", name: "El Salvador International", city: "San Salvador", country: "El Salvador", lat: 13.4409, lng: -89.0557 },
  { code: "MGA", name: "Augusto C. Sandino International", city: "Managua", country: "Nicaragua", lat: 12.1415, lng: -86.1681 },
  { code: "SJO", name: "Juan Santamaria International", city: "San Jose", country: "Costa Rica", lat: 9.9939, lng: -84.2088 },
  { code: "PTY", name: "Tocumen International", city: "Panama City", country: "Panama", lat: 9.0714, lng: -79.3835 },

  // Caribbean
  { code: "MBJ", name: "Sangster International", city: "Montego Bay", country: "Jamaica", lat: 18.5037, lng: -77.9134 },
  { code: "KIN", name: "Norman Manley International", city: "Kingston", country: "Jamaica", lat: 17.9357, lng: -76.7875 },
  { code: "NAS", name: "Lynden Pindling International", city: "Nassau", country: "Bahamas", lat: 25.0389, lng: -77.4662 },
  { code: "PUJ", name: "Punta Cana International", city: "Punta Cana", country: "Dominican Republic", lat: 18.5674, lng: -68.3634 },
  { code: "SDQ", name: "Las Americas International", city: "Santo Domingo", country: "Dominican Republic", lat: 18.4297, lng: -69.6689 },
  { code: "SJU", name: "Luis Munoz Marin International", city: "San Juan", country: "Puerto Rico", lat: 18.4394, lng: -66.0018 },
  { code: "BGI", name: "Grantley Adams International", city: "Bridgetown", country: "Barbados", lat: 13.0746, lng: -59.4925 },
  { code: "POS", name: "Piarco International", city: "Port of Spain", country: "Trinidad and Tobago", lat: 10.5954, lng: -61.3372 },
  { code: "ANU", name: "V.C. Bird International", city: "St. John's", country: "Antigua and Barbuda", lat: 17.1367, lng: -61.7927 },
  { code: "GEO", name: "Cheddi Jagan International", city: "Georgetown", country: "Guyana", lat: 6.4986, lng: -58.2541 },
  { code: "PBM", name: "Johan Adolf Pengel International", city: "Paramaribo", country: "Suriname", lat: 5.4528, lng: -55.1878 },
  { code: "HAV", name: "Jose Marti International", city: "Havana", country: "Cuba", lat: 22.9892, lng: -82.4091 },
  { code: "CUR", name: "Hato International", city: "Willemstad", country: "Curacao", lat: 12.1889, lng: -68.9598 },
  { code: "SXM", name: "Princess Juliana International", city: "Philipsburg", country: "Sint Maarten", lat: 18.0410, lng: -63.1089 },

  // South America
  { code: "GRU", name: "Sao Paulo Guarulhos International", city: "Sao Paulo", country: "Brazil", lat: -23.4356, lng: -46.4731 },
  { code: "CGH", name: "Congonhas Airport", city: "Sao Paulo", country: "Brazil", lat: -23.6261, lng: -46.6564 },
  { code: "GIG", name: "Galeao International", city: "Rio de Janeiro", country: "Brazil", lat: -22.8099, lng: -43.2505 },
  { code: "SDU", name: "Santos Dumont Airport", city: "Rio de Janeiro", country: "Brazil", lat: -22.9105, lng: -43.1631 },
  { code: "BSB", name: "Presidente Juscelino Kubitschek International", city: "Brasilia", country: "Brazil", lat: -15.8711, lng: -47.9186 },
  { code: "FOR", name: "Pinto Martins International", city: "Fortaleza", country: "Brazil", lat: -3.7763, lng: -38.5326 },
  { code: "SSA", name: "Deputado Luis Eduardo Magalhaes International", city: "Salvador", country: "Brazil", lat: -12.9086, lng: -38.3225 },
  { code: "REC", name: "Guararapes International", city: "Recife", country: "Brazil", lat: -8.1265, lng: -34.9237 },
  { code: "BEL", name: "Val de Cans International", city: "Belem", country: "Brazil", lat: -1.3792, lng: -48.4763 },
  { code: "MAO", name: "Eduardo Gomes International", city: "Manaus", country: "Brazil", lat: -3.0386, lng: -60.0497 },
  { code: "CWB", name: "Afonso Pena International", city: "Curitiba", country: "Brazil", lat: -25.5285, lng: -49.1758 },
  { code: "POA", name: "Salgado Filho International", city: "Porto Alegre", country: "Brazil", lat: -29.9944, lng: -51.1714 },
  { code: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "Argentina", lat: -34.8222, lng: -58.5358 },
  { code: "AEP", name: "Jorge Newbery Airfield", city: "Buenos Aires", country: "Argentina", lat: -34.5592, lng: -58.4156 },
  { code: "COR", name: "Ingeniero Aeronautico Ambrosio Taravella International", city: "Cordoba", country: "Argentina", lat: -31.3236, lng: -64.2080 },
  { code: "MDZ", name: "El Plumerillo International", city: "Mendoza", country: "Argentina", lat: -32.8317, lng: -68.7929 },
  { code: "SCL", name: "Arturo Merino Benitez International", city: "Santiago", country: "Chile", lat: -33.3930, lng: -70.7858 },
  { code: "PMC", name: "El Tepual Airport", city: "Puerto Montt", country: "Chile", lat: -41.4389, lng: -73.0940 },
  { code: "BOG", name: "El Dorado International", city: "Bogota", country: "Colombia", lat: 4.7016, lng: -74.1469 },
  { code: "MDE", name: "Jose Maria Cordova International", city: "Medellin", country: "Colombia", lat: 6.1645, lng: -75.4231 },
  { code: "CLO", name: "Alfonso Bonilla Aragon International", city: "Cali", country: "Colombia", lat: 3.5432, lng: -76.3816 },
  { code: "CTG", name: "Rafael Nunez International", city: "Cartagena", country: "Colombia", lat: 10.4424, lng: -75.5130 },
  { code: "LIM", name: "Jorge Chavez International", city: "Lima", country: "Peru", lat: -12.0219, lng: -77.1143 },
  { code: "CUZ", name: "Alejandro Velasco Astete International", city: "Cusco", country: "Peru", lat: -13.5357, lng: -71.9388 },
  { code: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "Ecuador", lat: -0.1292, lng: -78.3575 },
  { code: "GYE", name: "Jose Joaquin de Olmedo International", city: "Guayaquil", country: "Ecuador", lat: -2.1574, lng: -79.8836 },
  { code: "CCS", name: "Simon Bolivar International", city: "Caracas", country: "Venezuela", lat: 10.6012, lng: -66.9909 },
  { code: "ASU", name: "Silvio Pettirossi International", city: "Asuncion", country: "Paraguay", lat: -25.2400, lng: -57.5200 },
  { code: "MVD", name: "Carrasco International", city: "Montevideo", country: "Uruguay", lat: -34.8384, lng: -56.0308 },
  { code: "LPB", name: "El Alto International", city: "La Paz", country: "Bolivia", lat: -16.5133, lng: -68.1922 },
  { code: "VVI", name: "Viru Viru International", city: "Santa Cruz", country: "Bolivia", lat: -17.6448, lng: -63.1354 },

  // Oceania
  { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia", lat: -33.9399, lng: 151.1753 },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia", lat: -37.6690, lng: 144.8410 },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia", lat: -27.3842, lng: 153.1175 },
  { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia", lat: -31.9403, lng: 115.9669 },
  { code: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia", lat: -34.9450, lng: 138.5300 },
  { code: "OOL", name: "Gold Coast Airport", city: "Gold Coast", country: "Australia", lat: -28.1644, lng: 153.5047 },
  { code: "CNS", name: "Cairns Airport", city: "Cairns", country: "Australia", lat: -16.8858, lng: 145.7552 },
  { code: "HBA", name: "Hobart Airport", city: "Hobart", country: "Australia", lat: -42.8361, lng: 147.5108 },
  { code: "CBR", name: "Canberra Airport", city: "Canberra", country: "Australia", lat: -35.3069, lng: 149.1950 },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand", lat: -37.0082, lng: 174.7850 },
  { code: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "New Zealand", lat: -43.4894, lng: 172.5322 },
  { code: "WLG", name: "Wellington International Airport", city: "Wellington", country: "New Zealand", lat: -41.3272, lng: 174.8050 },
  { code: "ZQN", name: "Queenstown Airport", city: "Queenstown", country: "New Zealand", lat: -45.0211, lng: 168.7392 },
  { code: "NAN", name: "Nadi International Airport", city: "Nadi", country: "Fiji", lat: -17.7554, lng: 177.4431 },
  { code: "SUV", name: "Nausori International Airport", city: "Suva", country: "Fiji", lat: -18.0433, lng: 178.5592 },
  { code: "PPT", name: "Faa'a International Airport", city: "Papeete", country: "French Polynesia", lat: -17.5534, lng: -149.6066 },
  { code: "APW", name: "Faleolo International Airport", city: "Apia", country: "Samoa", lat: -13.8300, lng: -172.0083 },
  { code: "TBU", name: "Fua'amotu International Airport", city: "Nuku'alofa", country: "Tonga", lat: -21.2412, lng: -175.1496 },
  { code: "VLI", name: "Bauerfield International Airport", city: "Port Vila", country: "Vanuatu", lat: -17.6993, lng: 168.3200 },
  { code: "HIR", name: "Honiara International Airport", city: "Honiara", country: "Solomon Islands", lat: -9.4280, lng: 160.0548 },
  { code: "POM", name: "Jacksons International Airport", city: "Port Moresby", country: "Papua New Guinea", lat: -9.4434, lng: 147.2200 },
  { code: "GUM", name: "Antonio B. Won Pat International Airport", city: "Hagatna", country: "Guam", lat: 13.4834, lng: 144.7961 },
];

export function searchAirports(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return AIRPORTS_DB.filter(a =>
    a.code.toLowerCase().includes(q) ||
    a.city.toLowerCase().includes(q) ||
    a.name.toLowerCase().includes(q) ||
    a.country.toLowerCase().includes(q)
  ).slice(0, 8);
}
